/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package svc.ntuc.nlh.seo.bulkupload.model.impl;

import svc.ntuc.nlh.seo.bulkupload.model.NtucBulkUpload;
import svc.ntuc.nlh.seo.bulkupload.service.NtucBulkUploadLocalServiceUtil;

/**
 * The extended model base implementation for the NtucBulkUpload service. Represents a row in the &quot;ntuc_seo_NtucBulkUpload&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link NtucBulkUploadImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see NtucBulkUploadImpl
 * @see NtucBulkUpload
 * @generated
 */
public abstract class NtucBulkUploadBaseImpl
	extends NtucBulkUploadModelImpl implements NtucBulkUpload {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ntuc bulk upload model instance should use the <code>NtucBulkUpload</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			NtucBulkUploadLocalServiceUtil.addNtucBulkUpload(this);
		}
		else {
			NtucBulkUploadLocalServiceUtil.updateNtucBulkUpload(this);
		}
	}

}