/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package svc.ntuc.nlh.seo.bulkupload.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import svc.ntuc.nlh.seo.bulkupload.model.NtucBulkUpload;
import svc.ntuc.nlh.seo.bulkupload.model.NtucBulkUploadModel;

/**
 * The base model implementation for the NtucBulkUpload service. Represents a row in the &quot;ntuc_seo_NtucBulkUpload&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>NtucBulkUploadModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link NtucBulkUploadImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see NtucBulkUploadImpl
 * @generated
 */
public class NtucBulkUploadModelImpl
	extends BaseModelImpl<NtucBulkUpload> implements NtucBulkUploadModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ntuc bulk upload model instance should use the <code>NtucBulkUpload</code> interface instead.
	 */
	public static final String TABLE_NAME = "ntuc_seo_NtucBulkUpload";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"ntucBulkUploadId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"fileName", Types.VARCHAR}, {"rowData", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ntucBulkUploadId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("fileName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("rowData", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ntuc_seo_NtucBulkUpload (uuid_ VARCHAR(75) null,ntucBulkUploadId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,fileName VARCHAR(75) null,rowData STRING null)";

	public static final String TABLE_SQL_DROP =
		"drop table ntuc_seo_NtucBulkUpload";

	public static final String ORDER_BY_JPQL =
		" ORDER BY ntucBulkUpload.ntucBulkUploadId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ntuc_seo_NtucBulkUpload.ntucBulkUploadId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long NTUCBULKUPLOADID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public NtucBulkUploadModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _ntucBulkUploadId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setNtucBulkUploadId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _ntucBulkUploadId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return NtucBulkUpload.class;
	}

	@Override
	public String getModelClassName() {
		return NtucBulkUpload.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<NtucBulkUpload, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<NtucBulkUpload, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<NtucBulkUpload, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((NtucBulkUpload)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<NtucBulkUpload, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<NtucBulkUpload, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(NtucBulkUpload)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<NtucBulkUpload, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<NtucBulkUpload, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, NtucBulkUpload>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			NtucBulkUpload.class.getClassLoader(), NtucBulkUpload.class,
			ModelWrapper.class);

		try {
			Constructor<NtucBulkUpload> constructor =
				(Constructor<NtucBulkUpload>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<NtucBulkUpload, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<NtucBulkUpload, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<NtucBulkUpload, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<NtucBulkUpload, Object>>();
		Map<String, BiConsumer<NtucBulkUpload, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<NtucBulkUpload, ?>>();

		attributeGetterFunctions.put("uuid", NtucBulkUpload::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<NtucBulkUpload, String>)NtucBulkUpload::setUuid);
		attributeGetterFunctions.put(
			"ntucBulkUploadId", NtucBulkUpload::getNtucBulkUploadId);
		attributeSetterBiConsumers.put(
			"ntucBulkUploadId",
			(BiConsumer<NtucBulkUpload, Long>)
				NtucBulkUpload::setNtucBulkUploadId);
		attributeGetterFunctions.put("groupId", NtucBulkUpload::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<NtucBulkUpload, Long>)NtucBulkUpload::setGroupId);
		attributeGetterFunctions.put("companyId", NtucBulkUpload::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<NtucBulkUpload, Long>)NtucBulkUpload::setCompanyId);
		attributeGetterFunctions.put("userId", NtucBulkUpload::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<NtucBulkUpload, Long>)NtucBulkUpload::setUserId);
		attributeGetterFunctions.put("userName", NtucBulkUpload::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<NtucBulkUpload, String>)NtucBulkUpload::setUserName);
		attributeGetterFunctions.put(
			"createDate", NtucBulkUpload::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<NtucBulkUpload, Date>)NtucBulkUpload::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", NtucBulkUpload::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<NtucBulkUpload, Date>)NtucBulkUpload::setModifiedDate);
		attributeGetterFunctions.put("fileName", NtucBulkUpload::getFileName);
		attributeSetterBiConsumers.put(
			"fileName",
			(BiConsumer<NtucBulkUpload, String>)NtucBulkUpload::setFileName);
		attributeGetterFunctions.put("rowData", NtucBulkUpload::getRowData);
		attributeSetterBiConsumers.put(
			"rowData",
			(BiConsumer<NtucBulkUpload, String>)NtucBulkUpload::setRowData);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getNtucBulkUploadId() {
		return _ntucBulkUploadId;
	}

	@Override
	public void setNtucBulkUploadId(long ntucBulkUploadId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ntucBulkUploadId = ntucBulkUploadId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalNtucBulkUploadId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("ntucBulkUploadId"));
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getFileName() {
		if (_fileName == null) {
			return "";
		}
		else {
			return _fileName;
		}
	}

	@Override
	public void setFileName(String fileName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fileName = fileName;
	}

	@Override
	public String getRowData() {
		if (_rowData == null) {
			return "";
		}
		else {
			return _rowData;
		}
	}

	@Override
	public void setRowData(String rowData) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_rowData = rowData;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(NtucBulkUpload.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (entry.getValue() != getColumnValue(entry.getKey())) {
				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), NtucBulkUpload.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public NtucBulkUpload toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, NtucBulkUpload>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		NtucBulkUploadImpl ntucBulkUploadImpl = new NtucBulkUploadImpl();

		ntucBulkUploadImpl.setUuid(getUuid());
		ntucBulkUploadImpl.setNtucBulkUploadId(getNtucBulkUploadId());
		ntucBulkUploadImpl.setGroupId(getGroupId());
		ntucBulkUploadImpl.setCompanyId(getCompanyId());
		ntucBulkUploadImpl.setUserId(getUserId());
		ntucBulkUploadImpl.setUserName(getUserName());
		ntucBulkUploadImpl.setCreateDate(getCreateDate());
		ntucBulkUploadImpl.setModifiedDate(getModifiedDate());
		ntucBulkUploadImpl.setFileName(getFileName());
		ntucBulkUploadImpl.setRowData(getRowData());

		ntucBulkUploadImpl.resetOriginalValues();

		return ntucBulkUploadImpl;
	}

	@Override
	public int compareTo(NtucBulkUpload ntucBulkUpload) {
		int value = 0;

		if (getNtucBulkUploadId() < ntucBulkUpload.getNtucBulkUploadId()) {
			value = -1;
		}
		else if (getNtucBulkUploadId() > ntucBulkUpload.getNtucBulkUploadId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof NtucBulkUpload)) {
			return false;
		}

		NtucBulkUpload ntucBulkUpload = (NtucBulkUpload)object;

		long primaryKey = ntucBulkUpload.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<NtucBulkUpload> toCacheModel() {
		NtucBulkUploadCacheModel ntucBulkUploadCacheModel =
			new NtucBulkUploadCacheModel();

		ntucBulkUploadCacheModel.uuid = getUuid();

		String uuid = ntucBulkUploadCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			ntucBulkUploadCacheModel.uuid = null;
		}

		ntucBulkUploadCacheModel.ntucBulkUploadId = getNtucBulkUploadId();

		ntucBulkUploadCacheModel.groupId = getGroupId();

		ntucBulkUploadCacheModel.companyId = getCompanyId();

		ntucBulkUploadCacheModel.userId = getUserId();

		ntucBulkUploadCacheModel.userName = getUserName();

		String userName = ntucBulkUploadCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			ntucBulkUploadCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			ntucBulkUploadCacheModel.createDate = createDate.getTime();
		}
		else {
			ntucBulkUploadCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			ntucBulkUploadCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			ntucBulkUploadCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		ntucBulkUploadCacheModel.fileName = getFileName();

		String fileName = ntucBulkUploadCacheModel.fileName;

		if ((fileName != null) && (fileName.length() == 0)) {
			ntucBulkUploadCacheModel.fileName = null;
		}

		ntucBulkUploadCacheModel.rowData = getRowData();

		String rowData = ntucBulkUploadCacheModel.rowData;

		if ((rowData != null) && (rowData.length() == 0)) {
			ntucBulkUploadCacheModel.rowData = null;
		}

		return ntucBulkUploadCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<NtucBulkUpload, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<NtucBulkUpload, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<NtucBulkUpload, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((NtucBulkUpload)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<NtucBulkUpload, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<NtucBulkUpload, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<NtucBulkUpload, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((NtucBulkUpload)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, NtucBulkUpload>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private long _ntucBulkUploadId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _fileName;
	private String _rowData;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<NtucBulkUpload, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((NtucBulkUpload)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("ntucBulkUploadId", _ntucBulkUploadId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("fileName", _fileName);
		_columnOriginalValues.put("rowData", _rowData);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("ntucBulkUploadId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("fileName", 256L);

		columnBitmasks.put("rowData", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private NtucBulkUpload _escapedModel;

}