/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package svc.ntuc.nlh.parameter.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import svc.ntuc.nlh.parameter.model.Parameter;
import svc.ntuc.nlh.parameter.model.ParameterModel;

/**
 * The base model implementation for the Parameter service. Represents a row in the &quot;ntuc_parameter&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ParameterModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ParameterImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ParameterImpl
 * @generated
 */
public class ParameterModelImpl
	extends BaseModelImpl<Parameter> implements ParameterModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a parameter model instance should use the <code>Parameter</code> interface instead.
	 */
	public static final String TABLE_NAME = "ntuc_parameter";

	public static final Object[][] TABLE_COLUMNS = {
		{"parameterId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"parameterGroupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"createdBy", Types.BIGINT}, {"createdDate", Types.TIMESTAMP},
		{"modifiedBy", Types.BIGINT}, {"modifiedDate", Types.TIMESTAMP},
		{"paramCode", Types.VARCHAR}, {"paramName", Types.VARCHAR},
		{"paramValue", Types.VARCHAR}, {"description", Types.VARCHAR},
		{"deleted", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("parameterId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("parameterGroupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("paramCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("paramName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("paramValue", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("deleted", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ntuc_parameter (parameterId LONG not null primary key,groupId LONG,parameterGroupId LONG,companyId LONG,createdBy LONG,createdDate DATE null,modifiedBy LONG,modifiedDate DATE null,paramCode VARCHAR(75) null,paramName VARCHAR(75) null,paramValue VARCHAR(75) null,description VARCHAR(75) null,deleted BOOLEAN)";

	public static final String TABLE_SQL_DROP = "drop table ntuc_parameter";

	public static final String ORDER_BY_JPQL =
		" ORDER BY parameter.parameterId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ntuc_parameter.parameterId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long DELETED_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long PARAMCODE_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long PARAMETERGROUPID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)
	 */
	@Deprecated
	public static final long PARAMETERID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ParameterModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _parameterId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setParameterId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _parameterId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Parameter.class;
	}

	@Override
	public String getModelClassName() {
		return Parameter.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Parameter, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Parameter, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Parameter, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Parameter)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Parameter, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Parameter, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Parameter)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Parameter, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Parameter, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Parameter>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Parameter.class.getClassLoader(), Parameter.class,
			ModelWrapper.class);

		try {
			Constructor<Parameter> constructor =
				(Constructor<Parameter>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<Parameter, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Parameter, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Parameter, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Parameter, Object>>();
		Map<String, BiConsumer<Parameter, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Parameter, ?>>();

		attributeGetterFunctions.put("parameterId", Parameter::getParameterId);
		attributeSetterBiConsumers.put(
			"parameterId",
			(BiConsumer<Parameter, Long>)Parameter::setParameterId);
		attributeGetterFunctions.put("groupId", Parameter::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Parameter, Long>)Parameter::setGroupId);
		attributeGetterFunctions.put(
			"parameterGroupId", Parameter::getParameterGroupId);
		attributeSetterBiConsumers.put(
			"parameterGroupId",
			(BiConsumer<Parameter, Long>)Parameter::setParameterGroupId);
		attributeGetterFunctions.put("companyId", Parameter::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<Parameter, Long>)Parameter::setCompanyId);
		attributeGetterFunctions.put("createdBy", Parameter::getCreatedBy);
		attributeSetterBiConsumers.put(
			"createdBy", (BiConsumer<Parameter, Long>)Parameter::setCreatedBy);
		attributeGetterFunctions.put("createdDate", Parameter::getCreatedDate);
		attributeSetterBiConsumers.put(
			"createdDate",
			(BiConsumer<Parameter, Date>)Parameter::setCreatedDate);
		attributeGetterFunctions.put("modifiedBy", Parameter::getModifiedBy);
		attributeSetterBiConsumers.put(
			"modifiedBy",
			(BiConsumer<Parameter, Long>)Parameter::setModifiedBy);
		attributeGetterFunctions.put(
			"modifiedDate", Parameter::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<Parameter, Date>)Parameter::setModifiedDate);
		attributeGetterFunctions.put("paramCode", Parameter::getParamCode);
		attributeSetterBiConsumers.put(
			"paramCode",
			(BiConsumer<Parameter, String>)Parameter::setParamCode);
		attributeGetterFunctions.put("paramName", Parameter::getParamName);
		attributeSetterBiConsumers.put(
			"paramName",
			(BiConsumer<Parameter, String>)Parameter::setParamName);
		attributeGetterFunctions.put("paramValue", Parameter::getParamValue);
		attributeSetterBiConsumers.put(
			"paramValue",
			(BiConsumer<Parameter, String>)Parameter::setParamValue);
		attributeGetterFunctions.put("description", Parameter::getDescription);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<Parameter, String>)Parameter::setDescription);
		attributeGetterFunctions.put("deleted", Parameter::getDeleted);
		attributeSetterBiConsumers.put(
			"deleted", (BiConsumer<Parameter, Boolean>)Parameter::setDeleted);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getParameterId() {
		return _parameterId;
	}

	@Override
	public void setParameterId(long parameterId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_parameterId = parameterId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getParameterGroupId() {
		return _parameterGroupId;
	}

	@Override
	public void setParameterGroupId(long parameterGroupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_parameterGroupId = parameterGroupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalParameterGroupId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("parameterGroupId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdDate = createdDate;
	}

	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getParamCode() {
		if (_paramCode == null) {
			return "";
		}
		else {
			return _paramCode;
		}
	}

	@Override
	public void setParamCode(String paramCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_paramCode = paramCode;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalParamCode() {
		return getColumnOriginalValue("paramCode");
	}

	@Override
	public String getParamName() {
		if (_paramName == null) {
			return "";
		}
		else {
			return _paramName;
		}
	}

	@Override
	public void setParamName(String paramName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_paramName = paramName;
	}

	@Override
	public String getParamValue() {
		if (_paramValue == null) {
			return "";
		}
		else {
			return _paramValue;
		}
	}

	@Override
	public void setParamValue(String paramValue) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_paramValue = paramValue;
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_description = description;
	}

	@Override
	public Boolean getDeleted() {
		return _deleted;
	}

	@Override
	public void setDeleted(Boolean deleted) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_deleted = deleted;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public Boolean getOriginalDeleted() {
		return GetterUtil.getBoolean(
			this.<Boolean>getColumnOriginalValue("deleted"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (entry.getValue() != getColumnValue(entry.getKey())) {
				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Parameter.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Parameter toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Parameter>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ParameterImpl parameterImpl = new ParameterImpl();

		parameterImpl.setParameterId(getParameterId());
		parameterImpl.setGroupId(getGroupId());
		parameterImpl.setParameterGroupId(getParameterGroupId());
		parameterImpl.setCompanyId(getCompanyId());
		parameterImpl.setCreatedBy(getCreatedBy());
		parameterImpl.setCreatedDate(getCreatedDate());
		parameterImpl.setModifiedBy(getModifiedBy());
		parameterImpl.setModifiedDate(getModifiedDate());
		parameterImpl.setParamCode(getParamCode());
		parameterImpl.setParamName(getParamName());
		parameterImpl.setParamValue(getParamValue());
		parameterImpl.setDescription(getDescription());
		parameterImpl.setDeleted(getDeleted());

		parameterImpl.resetOriginalValues();

		return parameterImpl;
	}

	@Override
	public int compareTo(Parameter parameter) {
		long primaryKey = parameter.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Parameter)) {
			return false;
		}

		Parameter parameter = (Parameter)object;

		long primaryKey = parameter.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Parameter> toCacheModel() {
		ParameterCacheModel parameterCacheModel = new ParameterCacheModel();

		parameterCacheModel.parameterId = getParameterId();

		parameterCacheModel.groupId = getGroupId();

		parameterCacheModel.parameterGroupId = getParameterGroupId();

		parameterCacheModel.companyId = getCompanyId();

		parameterCacheModel.createdBy = getCreatedBy();

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			parameterCacheModel.createdDate = createdDate.getTime();
		}
		else {
			parameterCacheModel.createdDate = Long.MIN_VALUE;
		}

		parameterCacheModel.modifiedBy = getModifiedBy();

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			parameterCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			parameterCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		parameterCacheModel.paramCode = getParamCode();

		String paramCode = parameterCacheModel.paramCode;

		if ((paramCode != null) && (paramCode.length() == 0)) {
			parameterCacheModel.paramCode = null;
		}

		parameterCacheModel.paramName = getParamName();

		String paramName = parameterCacheModel.paramName;

		if ((paramName != null) && (paramName.length() == 0)) {
			parameterCacheModel.paramName = null;
		}

		parameterCacheModel.paramValue = getParamValue();

		String paramValue = parameterCacheModel.paramValue;

		if ((paramValue != null) && (paramValue.length() == 0)) {
			parameterCacheModel.paramValue = null;
		}

		parameterCacheModel.description = getDescription();

		String description = parameterCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			parameterCacheModel.description = null;
		}

		Boolean deleted = getDeleted();

		if (deleted != null) {
			parameterCacheModel.deleted = deleted;
		}

		return parameterCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Parameter, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Parameter, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Parameter, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Parameter)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Parameter, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Parameter, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Parameter, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Parameter)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Parameter>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _parameterId;
	private long _groupId;
	private long _parameterGroupId;
	private long _companyId;
	private long _createdBy;
	private Date _createdDate;
	private long _modifiedBy;
	private Date _modifiedDate;
	private String _paramCode;
	private String _paramName;
	private String _paramValue;
	private String _description;
	private Boolean _deleted;

	public <T> T getColumnValue(String columnName) {
		Function<Parameter, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Parameter)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("parameterId", _parameterId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("parameterGroupId", _parameterGroupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("createdDate", _createdDate);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("paramCode", _paramCode);
		_columnOriginalValues.put("paramName", _paramName);
		_columnOriginalValues.put("paramValue", _paramValue);
		_columnOriginalValues.put("description", _description);
		_columnOriginalValues.put("deleted", _deleted);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("parameterId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("parameterGroupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("createdBy", 16L);

		columnBitmasks.put("createdDate", 32L);

		columnBitmasks.put("modifiedBy", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("paramCode", 256L);

		columnBitmasks.put("paramName", 512L);

		columnBitmasks.put("paramValue", 1024L);

		columnBitmasks.put("description", 2048L);

		columnBitmasks.put("deleted", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Parameter _escapedModel;

}