/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package svc.ntuc.nlh.parameter.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import svc.ntuc.nlh.parameter.model.ParameterGroup;
import svc.ntuc.nlh.parameter.model.ParameterGroupModel;

/**
 * The base model implementation for the ParameterGroup service. Represents a row in the &quot;ntuc_parameter_group&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ParameterGroupModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ParameterGroupImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ParameterGroupImpl
 * @generated
 */
public class ParameterGroupModelImpl
	extends BaseModelImpl<ParameterGroup> implements ParameterGroupModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a parameter group model instance should use the <code>ParameterGroup</code> interface instead.
	 */
	public static final String TABLE_NAME = "ntuc_parameter_group";

	public static final Object[][] TABLE_COLUMNS = {
		{"parameterGroupId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"createdBy", Types.BIGINT},
		{"createdDate", Types.TIMESTAMP}, {"modifiedBy", Types.BIGINT},
		{"modifiedDate", Types.TIMESTAMP}, {"parentId", Types.BIGINT},
		{"groupName", Types.VARCHAR}, {"groupCode", Types.VARCHAR},
		{"description", Types.VARCHAR}, {"deleted", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("parameterGroupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("parentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("groupCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("deleted", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ntuc_parameter_group (parameterGroupId LONG not null primary key,groupId LONG,companyId LONG,createdBy LONG,createdDate DATE null,modifiedBy LONG,modifiedDate DATE null,parentId LONG,groupName VARCHAR(75) null,groupCode VARCHAR(75) null,description VARCHAR(75) null,deleted BOOLEAN)";

	public static final String TABLE_SQL_DROP =
		"drop table ntuc_parameter_group";

	public static final String ORDER_BY_JPQL =
		" ORDER BY parameterGroup.groupName ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ntuc_parameter_group.groupName ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long DELETED_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long GROUPCODE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long PARENTID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)
	 */
	@Deprecated
	public static final long GROUPNAME_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ParameterGroupModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _parameterGroupId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setParameterGroupId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _parameterGroupId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ParameterGroup.class;
	}

	@Override
	public String getModelClassName() {
		return ParameterGroup.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ParameterGroup, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ParameterGroup, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ParameterGroup, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ParameterGroup)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ParameterGroup, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ParameterGroup, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ParameterGroup)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ParameterGroup, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ParameterGroup, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, ParameterGroup>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			ParameterGroup.class.getClassLoader(), ParameterGroup.class,
			ModelWrapper.class);

		try {
			Constructor<ParameterGroup> constructor =
				(Constructor<ParameterGroup>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<ParameterGroup, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ParameterGroup, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ParameterGroup, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<ParameterGroup, Object>>();
		Map<String, BiConsumer<ParameterGroup, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<ParameterGroup, ?>>();

		attributeGetterFunctions.put(
			"parameterGroupId", ParameterGroup::getParameterGroupId);
		attributeSetterBiConsumers.put(
			"parameterGroupId",
			(BiConsumer<ParameterGroup, Long>)
				ParameterGroup::setParameterGroupId);
		attributeGetterFunctions.put("groupId", ParameterGroup::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<ParameterGroup, Long>)ParameterGroup::setGroupId);
		attributeGetterFunctions.put("companyId", ParameterGroup::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<ParameterGroup, Long>)ParameterGroup::setCompanyId);
		attributeGetterFunctions.put("createdBy", ParameterGroup::getCreatedBy);
		attributeSetterBiConsumers.put(
			"createdBy",
			(BiConsumer<ParameterGroup, Long>)ParameterGroup::setCreatedBy);
		attributeGetterFunctions.put(
			"createdDate", ParameterGroup::getCreatedDate);
		attributeSetterBiConsumers.put(
			"createdDate",
			(BiConsumer<ParameterGroup, Date>)ParameterGroup::setCreatedDate);
		attributeGetterFunctions.put(
			"modifiedBy", ParameterGroup::getModifiedBy);
		attributeSetterBiConsumers.put(
			"modifiedBy",
			(BiConsumer<ParameterGroup, Long>)ParameterGroup::setModifiedBy);
		attributeGetterFunctions.put(
			"modifiedDate", ParameterGroup::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<ParameterGroup, Date>)ParameterGroup::setModifiedDate);
		attributeGetterFunctions.put("parentId", ParameterGroup::getParentId);
		attributeSetterBiConsumers.put(
			"parentId",
			(BiConsumer<ParameterGroup, Long>)ParameterGroup::setParentId);
		attributeGetterFunctions.put("groupName", ParameterGroup::getGroupName);
		attributeSetterBiConsumers.put(
			"groupName",
			(BiConsumer<ParameterGroup, String>)ParameterGroup::setGroupName);
		attributeGetterFunctions.put("groupCode", ParameterGroup::getGroupCode);
		attributeSetterBiConsumers.put(
			"groupCode",
			(BiConsumer<ParameterGroup, String>)ParameterGroup::setGroupCode);
		attributeGetterFunctions.put(
			"description", ParameterGroup::getDescription);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<ParameterGroup, String>)ParameterGroup::setDescription);
		attributeGetterFunctions.put("deleted", ParameterGroup::getDeleted);
		attributeSetterBiConsumers.put(
			"deleted",
			(BiConsumer<ParameterGroup, Boolean>)ParameterGroup::setDeleted);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getParameterGroupId() {
		return _parameterGroupId;
	}

	@Override
	public void setParameterGroupId(long parameterGroupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_parameterGroupId = parameterGroupId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdDate = createdDate;
	}

	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getParentId() {
		return _parentId;
	}

	@Override
	public void setParentId(long parentId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_parentId = parentId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalParentId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("parentId"));
	}

	@Override
	public String getGroupName() {
		if (_groupName == null) {
			return "";
		}
		else {
			return _groupName;
		}
	}

	@Override
	public void setGroupName(String groupName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupName = groupName;
	}

	@Override
	public String getGroupCode() {
		if (_groupCode == null) {
			return "";
		}
		else {
			return _groupCode;
		}
	}

	@Override
	public void setGroupCode(String groupCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupCode = groupCode;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalGroupCode() {
		return getColumnOriginalValue("groupCode");
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_description = description;
	}

	@Override
	public Boolean getDeleted() {
		return _deleted;
	}

	@Override
	public void setDeleted(Boolean deleted) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_deleted = deleted;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public Boolean getOriginalDeleted() {
		return GetterUtil.getBoolean(
			this.<Boolean>getColumnOriginalValue("deleted"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (entry.getValue() != getColumnValue(entry.getKey())) {
				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ParameterGroup.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ParameterGroup toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ParameterGroup>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ParameterGroupImpl parameterGroupImpl = new ParameterGroupImpl();

		parameterGroupImpl.setParameterGroupId(getParameterGroupId());
		parameterGroupImpl.setGroupId(getGroupId());
		parameterGroupImpl.setCompanyId(getCompanyId());
		parameterGroupImpl.setCreatedBy(getCreatedBy());
		parameterGroupImpl.setCreatedDate(getCreatedDate());
		parameterGroupImpl.setModifiedBy(getModifiedBy());
		parameterGroupImpl.setModifiedDate(getModifiedDate());
		parameterGroupImpl.setParentId(getParentId());
		parameterGroupImpl.setGroupName(getGroupName());
		parameterGroupImpl.setGroupCode(getGroupCode());
		parameterGroupImpl.setDescription(getDescription());
		parameterGroupImpl.setDeleted(getDeleted());

		parameterGroupImpl.resetOriginalValues();

		return parameterGroupImpl;
	}

	@Override
	public int compareTo(ParameterGroup parameterGroup) {
		int value = 0;

		value = getGroupName().compareTo(parameterGroup.getGroupName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ParameterGroup)) {
			return false;
		}

		ParameterGroup parameterGroup = (ParameterGroup)object;

		long primaryKey = parameterGroup.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ParameterGroup> toCacheModel() {
		ParameterGroupCacheModel parameterGroupCacheModel =
			new ParameterGroupCacheModel();

		parameterGroupCacheModel.parameterGroupId = getParameterGroupId();

		parameterGroupCacheModel.groupId = getGroupId();

		parameterGroupCacheModel.companyId = getCompanyId();

		parameterGroupCacheModel.createdBy = getCreatedBy();

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			parameterGroupCacheModel.createdDate = createdDate.getTime();
		}
		else {
			parameterGroupCacheModel.createdDate = Long.MIN_VALUE;
		}

		parameterGroupCacheModel.modifiedBy = getModifiedBy();

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			parameterGroupCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			parameterGroupCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		parameterGroupCacheModel.parentId = getParentId();

		parameterGroupCacheModel.groupName = getGroupName();

		String groupName = parameterGroupCacheModel.groupName;

		if ((groupName != null) && (groupName.length() == 0)) {
			parameterGroupCacheModel.groupName = null;
		}

		parameterGroupCacheModel.groupCode = getGroupCode();

		String groupCode = parameterGroupCacheModel.groupCode;

		if ((groupCode != null) && (groupCode.length() == 0)) {
			parameterGroupCacheModel.groupCode = null;
		}

		parameterGroupCacheModel.description = getDescription();

		String description = parameterGroupCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			parameterGroupCacheModel.description = null;
		}

		Boolean deleted = getDeleted();

		if (deleted != null) {
			parameterGroupCacheModel.deleted = deleted;
		}

		return parameterGroupCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ParameterGroup, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ParameterGroup, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ParameterGroup, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((ParameterGroup)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<ParameterGroup, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<ParameterGroup, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ParameterGroup, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((ParameterGroup)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ParameterGroup>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _parameterGroupId;
	private long _groupId;
	private long _companyId;
	private long _createdBy;
	private Date _createdDate;
	private long _modifiedBy;
	private Date _modifiedDate;
	private long _parentId;
	private String _groupName;
	private String _groupCode;
	private String _description;
	private Boolean _deleted;

	public <T> T getColumnValue(String columnName) {
		Function<ParameterGroup, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ParameterGroup)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("parameterGroupId", _parameterGroupId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("createdDate", _createdDate);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("parentId", _parentId);
		_columnOriginalValues.put("groupName", _groupName);
		_columnOriginalValues.put("groupCode", _groupCode);
		_columnOriginalValues.put("description", _description);
		_columnOriginalValues.put("deleted", _deleted);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("parameterGroupId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("createdBy", 8L);

		columnBitmasks.put("createdDate", 16L);

		columnBitmasks.put("modifiedBy", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("parentId", 128L);

		columnBitmasks.put("groupName", 256L);

		columnBitmasks.put("groupCode", 512L);

		columnBitmasks.put("description", 1024L);

		columnBitmasks.put("deleted", 2048L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ParameterGroup _escapedModel;

}