/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package svc.ntuc.nlh.parameter.model.impl;

import svc.ntuc.nlh.parameter.model.ParameterGroup;
import svc.ntuc.nlh.parameter.service.ParameterGroupLocalServiceUtil;

/**
 * The extended model base implementation for the ParameterGroup service. Represents a row in the &quot;ntuc_parameter_group&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ParameterGroupImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ParameterGroupImpl
 * @see ParameterGroup
 * @generated
 */
public abstract class ParameterGroupBaseImpl
	extends ParameterGroupModelImpl implements ParameterGroup {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a parameter group model instance should use the <code>ParameterGroup</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ParameterGroupLocalServiceUtil.addParameterGroup(this);
		}
		else {
			ParameterGroupLocalServiceUtil.updateParameterGroup(this);
		}
	}

}