/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package svc.ntuc.nlh.parameter.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import svc.ntuc.nlh.parameter.model.ReservedParameter;
import svc.ntuc.nlh.parameter.model.ReservedParameterModel;

/**
 * The base model implementation for the ReservedParameter service. Represents a row in the &quot;ntuc_reserved_parameter&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ReservedParameterModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ReservedParameterImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ReservedParameterImpl
 * @generated
 */
public class ReservedParameterModelImpl
	extends BaseModelImpl<ReservedParameter> implements ReservedParameterModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a reserved parameter model instance should use the <code>ReservedParameter</code> interface instead.
	 */
	public static final String TABLE_NAME = "ntuc_reserved_parameter";

	public static final Object[][] TABLE_COLUMNS = {
		{"reservedParameterId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"parameterId", Types.BIGINT}, {"parameterGroupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"createdBy", Types.BIGINT},
		{"createdDate", Types.TIMESTAMP}, {"modifiedBy", Types.BIGINT},
		{"modifiedDate", Types.TIMESTAMP}, {"paramCode", Types.VARCHAR},
		{"reservedBy", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("reservedParameterId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("parameterId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("parameterGroupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createdDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("paramCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("reservedBy", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ntuc_reserved_parameter (reservedParameterId LONG not null primary key,groupId LONG,parameterId LONG,parameterGroupId LONG,companyId LONG,createdBy LONG,createdDate DATE null,modifiedBy LONG,modifiedDate DATE null,paramCode VARCHAR(75) null,reservedBy VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table ntuc_reserved_parameter";

	public static final String ORDER_BY_JPQL =
		" ORDER BY reservedParameter.reservedParameterId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ntuc_reserved_parameter.reservedParameterId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long PARAMCODE_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long PARAMETERGROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long RESERVEDBY_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)
	 */
	@Deprecated
	public static final long RESERVEDPARAMETERID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ReservedParameterModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _reservedParameterId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setReservedParameterId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _reservedParameterId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ReservedParameter.class;
	}

	@Override
	public String getModelClassName() {
		return ReservedParameter.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ReservedParameter, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ReservedParameter, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ReservedParameter, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ReservedParameter)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ReservedParameter, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ReservedParameter, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ReservedParameter)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ReservedParameter, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ReservedParameter, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, ReservedParameter>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			ReservedParameter.class.getClassLoader(), ReservedParameter.class,
			ModelWrapper.class);

		try {
			Constructor<ReservedParameter> constructor =
				(Constructor<ReservedParameter>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<ReservedParameter, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ReservedParameter, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ReservedParameter, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<ReservedParameter, Object>>();
		Map<String, BiConsumer<ReservedParameter, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<ReservedParameter, ?>>();

		attributeGetterFunctions.put(
			"reservedParameterId", ReservedParameter::getReservedParameterId);
		attributeSetterBiConsumers.put(
			"reservedParameterId",
			(BiConsumer<ReservedParameter, Long>)
				ReservedParameter::setReservedParameterId);
		attributeGetterFunctions.put("groupId", ReservedParameter::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<ReservedParameter, Long>)ReservedParameter::setGroupId);
		attributeGetterFunctions.put(
			"parameterId", ReservedParameter::getParameterId);
		attributeSetterBiConsumers.put(
			"parameterId",
			(BiConsumer<ReservedParameter, Long>)
				ReservedParameter::setParameterId);
		attributeGetterFunctions.put(
			"parameterGroupId", ReservedParameter::getParameterGroupId);
		attributeSetterBiConsumers.put(
			"parameterGroupId",
			(BiConsumer<ReservedParameter, Long>)
				ReservedParameter::setParameterGroupId);
		attributeGetterFunctions.put(
			"companyId", ReservedParameter::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<ReservedParameter, Long>)
				ReservedParameter::setCompanyId);
		attributeGetterFunctions.put(
			"createdBy", ReservedParameter::getCreatedBy);
		attributeSetterBiConsumers.put(
			"createdBy",
			(BiConsumer<ReservedParameter, Long>)
				ReservedParameter::setCreatedBy);
		attributeGetterFunctions.put(
			"createdDate", ReservedParameter::getCreatedDate);
		attributeSetterBiConsumers.put(
			"createdDate",
			(BiConsumer<ReservedParameter, Date>)
				ReservedParameter::setCreatedDate);
		attributeGetterFunctions.put(
			"modifiedBy", ReservedParameter::getModifiedBy);
		attributeSetterBiConsumers.put(
			"modifiedBy",
			(BiConsumer<ReservedParameter, Long>)
				ReservedParameter::setModifiedBy);
		attributeGetterFunctions.put(
			"modifiedDate", ReservedParameter::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<ReservedParameter, Date>)
				ReservedParameter::setModifiedDate);
		attributeGetterFunctions.put(
			"paramCode", ReservedParameter::getParamCode);
		attributeSetterBiConsumers.put(
			"paramCode",
			(BiConsumer<ReservedParameter, String>)
				ReservedParameter::setParamCode);
		attributeGetterFunctions.put(
			"reservedBy", ReservedParameter::getReservedBy);
		attributeSetterBiConsumers.put(
			"reservedBy",
			(BiConsumer<ReservedParameter, String>)
				ReservedParameter::setReservedBy);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getReservedParameterId() {
		return _reservedParameterId;
	}

	@Override
	public void setReservedParameterId(long reservedParameterId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_reservedParameterId = reservedParameterId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@Override
	public long getParameterId() {
		return _parameterId;
	}

	@Override
	public void setParameterId(long parameterId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_parameterId = parameterId;
	}

	@Override
	public long getParameterGroupId() {
		return _parameterGroupId;
	}

	@Override
	public void setParameterGroupId(long parameterGroupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_parameterGroupId = parameterGroupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalParameterGroupId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("parameterGroupId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdBy = createdBy;
	}

	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createdDate = createdDate;
	}

	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getParamCode() {
		if (_paramCode == null) {
			return "";
		}
		else {
			return _paramCode;
		}
	}

	@Override
	public void setParamCode(String paramCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_paramCode = paramCode;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalParamCode() {
		return getColumnOriginalValue("paramCode");
	}

	@Override
	public String getReservedBy() {
		if (_reservedBy == null) {
			return "";
		}
		else {
			return _reservedBy;
		}
	}

	@Override
	public void setReservedBy(String reservedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_reservedBy = reservedBy;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalReservedBy() {
		return getColumnOriginalValue("reservedBy");
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (entry.getValue() != getColumnValue(entry.getKey())) {
				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ReservedParameter.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ReservedParameter toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ReservedParameter>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ReservedParameterImpl reservedParameterImpl =
			new ReservedParameterImpl();

		reservedParameterImpl.setReservedParameterId(getReservedParameterId());
		reservedParameterImpl.setGroupId(getGroupId());
		reservedParameterImpl.setParameterId(getParameterId());
		reservedParameterImpl.setParameterGroupId(getParameterGroupId());
		reservedParameterImpl.setCompanyId(getCompanyId());
		reservedParameterImpl.setCreatedBy(getCreatedBy());
		reservedParameterImpl.setCreatedDate(getCreatedDate());
		reservedParameterImpl.setModifiedBy(getModifiedBy());
		reservedParameterImpl.setModifiedDate(getModifiedDate());
		reservedParameterImpl.setParamCode(getParamCode());
		reservedParameterImpl.setReservedBy(getReservedBy());

		reservedParameterImpl.resetOriginalValues();

		return reservedParameterImpl;
	}

	@Override
	public int compareTo(ReservedParameter reservedParameter) {
		long primaryKey = reservedParameter.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ReservedParameter)) {
			return false;
		}

		ReservedParameter reservedParameter = (ReservedParameter)object;

		long primaryKey = reservedParameter.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ReservedParameter> toCacheModel() {
		ReservedParameterCacheModel reservedParameterCacheModel =
			new ReservedParameterCacheModel();

		reservedParameterCacheModel.reservedParameterId =
			getReservedParameterId();

		reservedParameterCacheModel.groupId = getGroupId();

		reservedParameterCacheModel.parameterId = getParameterId();

		reservedParameterCacheModel.parameterGroupId = getParameterGroupId();

		reservedParameterCacheModel.companyId = getCompanyId();

		reservedParameterCacheModel.createdBy = getCreatedBy();

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			reservedParameterCacheModel.createdDate = createdDate.getTime();
		}
		else {
			reservedParameterCacheModel.createdDate = Long.MIN_VALUE;
		}

		reservedParameterCacheModel.modifiedBy = getModifiedBy();

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			reservedParameterCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			reservedParameterCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		reservedParameterCacheModel.paramCode = getParamCode();

		String paramCode = reservedParameterCacheModel.paramCode;

		if ((paramCode != null) && (paramCode.length() == 0)) {
			reservedParameterCacheModel.paramCode = null;
		}

		reservedParameterCacheModel.reservedBy = getReservedBy();

		String reservedBy = reservedParameterCacheModel.reservedBy;

		if ((reservedBy != null) && (reservedBy.length() == 0)) {
			reservedParameterCacheModel.reservedBy = null;
		}

		return reservedParameterCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ReservedParameter, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ReservedParameter, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ReservedParameter, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((ReservedParameter)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<ReservedParameter, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<ReservedParameter, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ReservedParameter, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((ReservedParameter)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ReservedParameter>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _reservedParameterId;
	private long _groupId;
	private long _parameterId;
	private long _parameterGroupId;
	private long _companyId;
	private long _createdBy;
	private Date _createdDate;
	private long _modifiedBy;
	private Date _modifiedDate;
	private String _paramCode;
	private String _reservedBy;

	public <T> T getColumnValue(String columnName) {
		Function<ReservedParameter, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ReservedParameter)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("reservedParameterId", _reservedParameterId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("parameterId", _parameterId);
		_columnOriginalValues.put("parameterGroupId", _parameterGroupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createdBy", _createdBy);
		_columnOriginalValues.put("createdDate", _createdDate);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("paramCode", _paramCode);
		_columnOriginalValues.put("reservedBy", _reservedBy);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("reservedParameterId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("parameterId", 4L);

		columnBitmasks.put("parameterGroupId", 8L);

		columnBitmasks.put("companyId", 16L);

		columnBitmasks.put("createdBy", 32L);

		columnBitmasks.put("createdDate", 64L);

		columnBitmasks.put("modifiedBy", 128L);

		columnBitmasks.put("modifiedDate", 256L);

		columnBitmasks.put("paramCode", 512L);

		columnBitmasks.put("reservedBy", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ReservedParameter _escapedModel;

}