/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ntuc.notification.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import com.ntuc.notification.model.AuditLog;
import com.ntuc.notification.model.AuditLogDetailsJsonBlobModel;
import com.ntuc.notification.model.AuditLogModel;
import com.ntuc.notification.model.AuditLogStackTraceTruncatedBlobModel;
import com.ntuc.notification.service.AuditLogLocalServiceUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the AuditLog service. Represents a row in the &quot;ntuc_audit_log&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AuditLogModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AuditLogImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AuditLogImpl
 * @generated
 */
public class AuditLogModelImpl
	extends BaseModelImpl<AuditLog> implements AuditLogModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a audit log model instance should use the <code>AuditLog</code> interface instead.
	 */
	public static final String TABLE_NAME = "ntuc_audit_log";

	public static final Object[][] TABLE_COLUMNS = {
		{"auditLogId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"courseCode", Types.VARCHAR}, {"ntucDTId", Types.BIGINT},
		{"startTimeMs", Types.BIGINT}, {"endTimeMs", Types.BIGINT},
		{"durationMs", Types.BIGINT}, {"correlationId", Types.VARCHAR},
		{"jobRunId", Types.VARCHAR}, {"requestId", Types.VARCHAR},
		{"eventId", Types.VARCHAR}, {"severity", Types.VARCHAR},
		{"status", Types.VARCHAR}, {"step", Types.VARCHAR},
		{"category", Types.VARCHAR}, {"message", Types.VARCHAR},
		{"errorCode", Types.VARCHAR}, {"errorMessage", Types.VARCHAR},
		{"exceptionClass", Types.VARCHAR}, {"alertFingerprint", Types.VARCHAR},
		{"stackTraceHash", Types.VARCHAR}, {"stackTraceTruncated", Types.BLOB},
		{"detailsJson", Types.BLOB}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("auditLogId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("courseCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ntucDTId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("startTimeMs", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("endTimeMs", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("durationMs", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("correlationId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("jobRunId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("requestId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("eventId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("severity", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("step", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("category", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("message", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("errorCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("errorMessage", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("exceptionClass", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("alertFingerprint", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("stackTraceHash", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("stackTraceTruncated", Types.BLOB);
		TABLE_COLUMNS_MAP.put("detailsJson", Types.BLOB);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ntuc_audit_log (auditLogId LONG not null primary key,createDate DATE null,modifiedDate DATE null,groupId LONG,companyId LONG,userId LONG,courseCode VARCHAR(75) null,ntucDTId LONG,startTimeMs LONG,endTimeMs LONG,durationMs LONG,correlationId VARCHAR(75) null,jobRunId VARCHAR(75) null,requestId VARCHAR(75) null,eventId VARCHAR(75) null,severity VARCHAR(75) null,status VARCHAR(75) null,step VARCHAR(75) null,category VARCHAR(75) null,message VARCHAR(75) null,errorCode VARCHAR(75) null,errorMessage VARCHAR(75) null,exceptionClass VARCHAR(75) null,alertFingerprint VARCHAR(75) null,stackTraceHash VARCHAR(75) null,stackTraceTruncated BLOB,detailsJson BLOB)";

	public static final String TABLE_SQL_DROP = "drop table ntuc_audit_log";

	public static final String ORDER_BY_JPQL =
		" ORDER BY auditLog.startTimeMs DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ntuc_audit_log.startTimeMs DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long ALERTFINGERPRINT_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long CATEGORY_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long CORRELATIONID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long COURSECODE_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long ERRORCODE_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long EVENTID_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long JOBRUNID_COLUMN_BITMASK = 128L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long NTUCDTID_COLUMN_BITMASK = 256L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long REQUESTID_COLUMN_BITMASK = 512L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long SEVERITY_COLUMN_BITMASK = 1024L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long STARTTIMEMS_COLUMN_BITMASK = 2048L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long STATUS_COLUMN_BITMASK = 4096L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long STEP_COLUMN_BITMASK = 8192L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public AuditLogModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _auditLogId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAuditLogId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _auditLogId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AuditLog.class;
	}

	@Override
	public String getModelClassName() {
		return AuditLog.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AuditLog, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AuditLog, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AuditLog, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((AuditLog)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AuditLog, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AuditLog, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AuditLog)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AuditLog, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AuditLog, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, AuditLog>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			AuditLog.class.getClassLoader(), AuditLog.class,
			ModelWrapper.class);

		try {
			Constructor<AuditLog> constructor =
				(Constructor<AuditLog>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<AuditLog, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<AuditLog, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<AuditLog, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<AuditLog, Object>>();
		Map<String, BiConsumer<AuditLog, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<AuditLog, ?>>();

		attributeGetterFunctions.put("auditLogId", AuditLog::getAuditLogId);
		attributeSetterBiConsumers.put(
			"auditLogId", (BiConsumer<AuditLog, Long>)AuditLog::setAuditLogId);
		attributeGetterFunctions.put("createDate", AuditLog::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<AuditLog, Date>)AuditLog::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", AuditLog::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<AuditLog, Date>)AuditLog::setModifiedDate);
		attributeGetterFunctions.put("groupId", AuditLog::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<AuditLog, Long>)AuditLog::setGroupId);
		attributeGetterFunctions.put("companyId", AuditLog::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<AuditLog, Long>)AuditLog::setCompanyId);
		attributeGetterFunctions.put("userId", AuditLog::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<AuditLog, Long>)AuditLog::setUserId);
		attributeGetterFunctions.put("courseCode", AuditLog::getCourseCode);
		attributeSetterBiConsumers.put(
			"courseCode",
			(BiConsumer<AuditLog, String>)AuditLog::setCourseCode);
		attributeGetterFunctions.put("ntucDTId", AuditLog::getNtucDTId);
		attributeSetterBiConsumers.put(
			"ntucDTId", (BiConsumer<AuditLog, Long>)AuditLog::setNtucDTId);
		attributeGetterFunctions.put("startTimeMs", AuditLog::getStartTimeMs);
		attributeSetterBiConsumers.put(
			"startTimeMs",
			(BiConsumer<AuditLog, Long>)AuditLog::setStartTimeMs);
		attributeGetterFunctions.put("endTimeMs", AuditLog::getEndTimeMs);
		attributeSetterBiConsumers.put(
			"endTimeMs", (BiConsumer<AuditLog, Long>)AuditLog::setEndTimeMs);
		attributeGetterFunctions.put("durationMs", AuditLog::getDurationMs);
		attributeSetterBiConsumers.put(
			"durationMs", (BiConsumer<AuditLog, Long>)AuditLog::setDurationMs);
		attributeGetterFunctions.put(
			"correlationId", AuditLog::getCorrelationId);
		attributeSetterBiConsumers.put(
			"correlationId",
			(BiConsumer<AuditLog, String>)AuditLog::setCorrelationId);
		attributeGetterFunctions.put("jobRunId", AuditLog::getJobRunId);
		attributeSetterBiConsumers.put(
			"jobRunId", (BiConsumer<AuditLog, String>)AuditLog::setJobRunId);
		attributeGetterFunctions.put("requestId", AuditLog::getRequestId);
		attributeSetterBiConsumers.put(
			"requestId", (BiConsumer<AuditLog, String>)AuditLog::setRequestId);
		attributeGetterFunctions.put("eventId", AuditLog::getEventId);
		attributeSetterBiConsumers.put(
			"eventId", (BiConsumer<AuditLog, String>)AuditLog::setEventId);
		attributeGetterFunctions.put("severity", AuditLog::getSeverity);
		attributeSetterBiConsumers.put(
			"severity", (BiConsumer<AuditLog, String>)AuditLog::setSeverity);
		attributeGetterFunctions.put("status", AuditLog::getStatus);
		attributeSetterBiConsumers.put(
			"status", (BiConsumer<AuditLog, String>)AuditLog::setStatus);
		attributeGetterFunctions.put("step", AuditLog::getStep);
		attributeSetterBiConsumers.put(
			"step", (BiConsumer<AuditLog, String>)AuditLog::setStep);
		attributeGetterFunctions.put("category", AuditLog::getCategory);
		attributeSetterBiConsumers.put(
			"category", (BiConsumer<AuditLog, String>)AuditLog::setCategory);
		attributeGetterFunctions.put("message", AuditLog::getMessage);
		attributeSetterBiConsumers.put(
			"message", (BiConsumer<AuditLog, String>)AuditLog::setMessage);
		attributeGetterFunctions.put("errorCode", AuditLog::getErrorCode);
		attributeSetterBiConsumers.put(
			"errorCode", (BiConsumer<AuditLog, String>)AuditLog::setErrorCode);
		attributeGetterFunctions.put("errorMessage", AuditLog::getErrorMessage);
		attributeSetterBiConsumers.put(
			"errorMessage",
			(BiConsumer<AuditLog, String>)AuditLog::setErrorMessage);
		attributeGetterFunctions.put(
			"exceptionClass", AuditLog::getExceptionClass);
		attributeSetterBiConsumers.put(
			"exceptionClass",
			(BiConsumer<AuditLog, String>)AuditLog::setExceptionClass);
		attributeGetterFunctions.put(
			"alertFingerprint", AuditLog::getAlertFingerprint);
		attributeSetterBiConsumers.put(
			"alertFingerprint",
			(BiConsumer<AuditLog, String>)AuditLog::setAlertFingerprint);
		attributeGetterFunctions.put(
			"stackTraceHash", AuditLog::getStackTraceHash);
		attributeSetterBiConsumers.put(
			"stackTraceHash",
			(BiConsumer<AuditLog, String>)AuditLog::setStackTraceHash);
		attributeGetterFunctions.put(
			"stackTraceTruncated", AuditLog::getStackTraceTruncated);
		attributeSetterBiConsumers.put(
			"stackTraceTruncated",
			(BiConsumer<AuditLog, Blob>)AuditLog::setStackTraceTruncated);
		attributeGetterFunctions.put("detailsJson", AuditLog::getDetailsJson);
		attributeSetterBiConsumers.put(
			"detailsJson",
			(BiConsumer<AuditLog, Blob>)AuditLog::setDetailsJson);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getAuditLogId() {
		return _auditLogId;
	}

	@Override
	public void setAuditLogId(long auditLogId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_auditLogId = auditLogId;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getCourseCode() {
		if (_courseCode == null) {
			return "";
		}
		else {
			return _courseCode;
		}
	}

	@Override
	public void setCourseCode(String courseCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_courseCode = courseCode;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalCourseCode() {
		return getColumnOriginalValue("courseCode");
	}

	@Override
	public long getNtucDTId() {
		return _ntucDTId;
	}

	@Override
	public void setNtucDTId(long ntucDTId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ntucDTId = ntucDTId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalNtucDTId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("ntucDTId"));
	}

	@Override
	public long getStartTimeMs() {
		return _startTimeMs;
	}

	@Override
	public void setStartTimeMs(long startTimeMs) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_startTimeMs = startTimeMs;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalStartTimeMs() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("startTimeMs"));
	}

	@Override
	public long getEndTimeMs() {
		return _endTimeMs;
	}

	@Override
	public void setEndTimeMs(long endTimeMs) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_endTimeMs = endTimeMs;
	}

	@Override
	public long getDurationMs() {
		return _durationMs;
	}

	@Override
	public void setDurationMs(long durationMs) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_durationMs = durationMs;
	}

	@Override
	public String getCorrelationId() {
		if (_correlationId == null) {
			return "";
		}
		else {
			return _correlationId;
		}
	}

	@Override
	public void setCorrelationId(String correlationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_correlationId = correlationId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalCorrelationId() {
		return getColumnOriginalValue("correlationId");
	}

	@Override
	public String getJobRunId() {
		if (_jobRunId == null) {
			return "";
		}
		else {
			return _jobRunId;
		}
	}

	@Override
	public void setJobRunId(String jobRunId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_jobRunId = jobRunId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalJobRunId() {
		return getColumnOriginalValue("jobRunId");
	}

	@Override
	public String getRequestId() {
		if (_requestId == null) {
			return "";
		}
		else {
			return _requestId;
		}
	}

	@Override
	public void setRequestId(String requestId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_requestId = requestId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalRequestId() {
		return getColumnOriginalValue("requestId");
	}

	@Override
	public String getEventId() {
		if (_eventId == null) {
			return "";
		}
		else {
			return _eventId;
		}
	}

	@Override
	public void setEventId(String eventId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_eventId = eventId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalEventId() {
		return getColumnOriginalValue("eventId");
	}

	@Override
	public String getSeverity() {
		if (_severity == null) {
			return "";
		}
		else {
			return _severity;
		}
	}

	@Override
	public void setSeverity(String severity) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_severity = severity;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalSeverity() {
		return getColumnOriginalValue("severity");
	}

	@Override
	public String getStatus() {
		if (_status == null) {
			return "";
		}
		else {
			return _status;
		}
	}

	@Override
	public void setStatus(String status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalStatus() {
		return getColumnOriginalValue("status");
	}

	@Override
	public String getStep() {
		if (_step == null) {
			return "";
		}
		else {
			return _step;
		}
	}

	@Override
	public void setStep(String step) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_step = step;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalStep() {
		return getColumnOriginalValue("step");
	}

	@Override
	public String getCategory() {
		if (_category == null) {
			return "";
		}
		else {
			return _category;
		}
	}

	@Override
	public void setCategory(String category) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_category = category;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalCategory() {
		return getColumnOriginalValue("category");
	}

	@Override
	public String getMessage() {
		if (_message == null) {
			return "";
		}
		else {
			return _message;
		}
	}

	@Override
	public void setMessage(String message) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_message = message;
	}

	@Override
	public String getErrorCode() {
		if (_errorCode == null) {
			return "";
		}
		else {
			return _errorCode;
		}
	}

	@Override
	public void setErrorCode(String errorCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_errorCode = errorCode;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalErrorCode() {
		return getColumnOriginalValue("errorCode");
	}

	@Override
	public String getErrorMessage() {
		if (_errorMessage == null) {
			return "";
		}
		else {
			return _errorMessage;
		}
	}

	@Override
	public void setErrorMessage(String errorMessage) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_errorMessage = errorMessage;
	}

	@Override
	public String getExceptionClass() {
		if (_exceptionClass == null) {
			return "";
		}
		else {
			return _exceptionClass;
		}
	}

	@Override
	public void setExceptionClass(String exceptionClass) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_exceptionClass = exceptionClass;
	}

	@Override
	public String getAlertFingerprint() {
		if (_alertFingerprint == null) {
			return "";
		}
		else {
			return _alertFingerprint;
		}
	}

	@Override
	public void setAlertFingerprint(String alertFingerprint) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_alertFingerprint = alertFingerprint;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalAlertFingerprint() {
		return getColumnOriginalValue("alertFingerprint");
	}

	@Override
	public String getStackTraceHash() {
		if (_stackTraceHash == null) {
			return "";
		}
		else {
			return _stackTraceHash;
		}
	}

	@Override
	public void setStackTraceHash(String stackTraceHash) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_stackTraceHash = stackTraceHash;
	}

	@Override
	public Blob getStackTraceTruncated() {
		if (_stackTraceTruncatedBlobModel == null) {
			try {
				_stackTraceTruncatedBlobModel =
					AuditLogLocalServiceUtil.getStackTraceTruncatedBlobModel(
						getPrimaryKey());
			}
			catch (Exception exception) {
			}
		}

		Blob blob = null;

		if (_stackTraceTruncatedBlobModel != null) {
			blob = _stackTraceTruncatedBlobModel.getStackTraceTruncatedBlob();
		}

		return blob;
	}

	@Override
	public void setStackTraceTruncated(Blob stackTraceTruncated) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		if (_stackTraceTruncatedBlobModel == null) {
			_stackTraceTruncatedBlobModel =
				new AuditLogStackTraceTruncatedBlobModel(
					getPrimaryKey(), stackTraceTruncated);
		}
		else {
			_stackTraceTruncatedBlobModel.setStackTraceTruncatedBlob(
				stackTraceTruncated);
		}
	}

	@Override
	public Blob getDetailsJson() {
		if (_detailsJsonBlobModel == null) {
			try {
				_detailsJsonBlobModel =
					AuditLogLocalServiceUtil.getDetailsJsonBlobModel(
						getPrimaryKey());
			}
			catch (Exception exception) {
			}
		}

		Blob blob = null;

		if (_detailsJsonBlobModel != null) {
			blob = _detailsJsonBlobModel.getDetailsJsonBlob();
		}

		return blob;
	}

	@Override
	public void setDetailsJson(Blob detailsJson) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		if (_detailsJsonBlobModel == null) {
			_detailsJsonBlobModel = new AuditLogDetailsJsonBlobModel(
				getPrimaryKey(), detailsJson);
		}
		else {
			_detailsJsonBlobModel.setDetailsJsonBlob(detailsJson);
		}
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (entry.getValue() != getColumnValue(entry.getKey())) {
				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), AuditLog.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AuditLog toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AuditLog>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AuditLogImpl auditLogImpl = new AuditLogImpl();

		auditLogImpl.setAuditLogId(getAuditLogId());
		auditLogImpl.setCreateDate(getCreateDate());
		auditLogImpl.setModifiedDate(getModifiedDate());
		auditLogImpl.setGroupId(getGroupId());
		auditLogImpl.setCompanyId(getCompanyId());
		auditLogImpl.setUserId(getUserId());
		auditLogImpl.setCourseCode(getCourseCode());
		auditLogImpl.setNtucDTId(getNtucDTId());
		auditLogImpl.setStartTimeMs(getStartTimeMs());
		auditLogImpl.setEndTimeMs(getEndTimeMs());
		auditLogImpl.setDurationMs(getDurationMs());
		auditLogImpl.setCorrelationId(getCorrelationId());
		auditLogImpl.setJobRunId(getJobRunId());
		auditLogImpl.setRequestId(getRequestId());
		auditLogImpl.setEventId(getEventId());
		auditLogImpl.setSeverity(getSeverity());
		auditLogImpl.setStatus(getStatus());
		auditLogImpl.setStep(getStep());
		auditLogImpl.setCategory(getCategory());
		auditLogImpl.setMessage(getMessage());
		auditLogImpl.setErrorCode(getErrorCode());
		auditLogImpl.setErrorMessage(getErrorMessage());
		auditLogImpl.setExceptionClass(getExceptionClass());
		auditLogImpl.setAlertFingerprint(getAlertFingerprint());
		auditLogImpl.setStackTraceHash(getStackTraceHash());

		auditLogImpl.resetOriginalValues();

		return auditLogImpl;
	}

	@Override
	public int compareTo(AuditLog auditLog) {
		int value = 0;

		if (getStartTimeMs() < auditLog.getStartTimeMs()) {
			value = -1;
		}
		else if (getStartTimeMs() > auditLog.getStartTimeMs()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof AuditLog)) {
			return false;
		}

		AuditLog auditLog = (AuditLog)object;

		long primaryKey = auditLog.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_stackTraceTruncatedBlobModel = null;

		_detailsJsonBlobModel = null;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<AuditLog> toCacheModel() {
		AuditLogCacheModel auditLogCacheModel = new AuditLogCacheModel();

		auditLogCacheModel.auditLogId = getAuditLogId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			auditLogCacheModel.createDate = createDate.getTime();
		}
		else {
			auditLogCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			auditLogCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			auditLogCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		auditLogCacheModel.groupId = getGroupId();

		auditLogCacheModel.companyId = getCompanyId();

		auditLogCacheModel.userId = getUserId();

		auditLogCacheModel.courseCode = getCourseCode();

		String courseCode = auditLogCacheModel.courseCode;

		if ((courseCode != null) && (courseCode.length() == 0)) {
			auditLogCacheModel.courseCode = null;
		}

		auditLogCacheModel.ntucDTId = getNtucDTId();

		auditLogCacheModel.startTimeMs = getStartTimeMs();

		auditLogCacheModel.endTimeMs = getEndTimeMs();

		auditLogCacheModel.durationMs = getDurationMs();

		auditLogCacheModel.correlationId = getCorrelationId();

		String correlationId = auditLogCacheModel.correlationId;

		if ((correlationId != null) && (correlationId.length() == 0)) {
			auditLogCacheModel.correlationId = null;
		}

		auditLogCacheModel.jobRunId = getJobRunId();

		String jobRunId = auditLogCacheModel.jobRunId;

		if ((jobRunId != null) && (jobRunId.length() == 0)) {
			auditLogCacheModel.jobRunId = null;
		}

		auditLogCacheModel.requestId = getRequestId();

		String requestId = auditLogCacheModel.requestId;

		if ((requestId != null) && (requestId.length() == 0)) {
			auditLogCacheModel.requestId = null;
		}

		auditLogCacheModel.eventId = getEventId();

		String eventId = auditLogCacheModel.eventId;

		if ((eventId != null) && (eventId.length() == 0)) {
			auditLogCacheModel.eventId = null;
		}

		auditLogCacheModel.severity = getSeverity();

		String severity = auditLogCacheModel.severity;

		if ((severity != null) && (severity.length() == 0)) {
			auditLogCacheModel.severity = null;
		}

		auditLogCacheModel.status = getStatus();

		String status = auditLogCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			auditLogCacheModel.status = null;
		}

		auditLogCacheModel.step = getStep();

		String step = auditLogCacheModel.step;

		if ((step != null) && (step.length() == 0)) {
			auditLogCacheModel.step = null;
		}

		auditLogCacheModel.category = getCategory();

		String category = auditLogCacheModel.category;

		if ((category != null) && (category.length() == 0)) {
			auditLogCacheModel.category = null;
		}

		auditLogCacheModel.message = getMessage();

		String message = auditLogCacheModel.message;

		if ((message != null) && (message.length() == 0)) {
			auditLogCacheModel.message = null;
		}

		auditLogCacheModel.errorCode = getErrorCode();

		String errorCode = auditLogCacheModel.errorCode;

		if ((errorCode != null) && (errorCode.length() == 0)) {
			auditLogCacheModel.errorCode = null;
		}

		auditLogCacheModel.errorMessage = getErrorMessage();

		String errorMessage = auditLogCacheModel.errorMessage;

		if ((errorMessage != null) && (errorMessage.length() == 0)) {
			auditLogCacheModel.errorMessage = null;
		}

		auditLogCacheModel.exceptionClass = getExceptionClass();

		String exceptionClass = auditLogCacheModel.exceptionClass;

		if ((exceptionClass != null) && (exceptionClass.length() == 0)) {
			auditLogCacheModel.exceptionClass = null;
		}

		auditLogCacheModel.alertFingerprint = getAlertFingerprint();

		String alertFingerprint = auditLogCacheModel.alertFingerprint;

		if ((alertFingerprint != null) && (alertFingerprint.length() == 0)) {
			auditLogCacheModel.alertFingerprint = null;
		}

		auditLogCacheModel.stackTraceHash = getStackTraceHash();

		String stackTraceHash = auditLogCacheModel.stackTraceHash;

		if ((stackTraceHash != null) && (stackTraceHash.length() == 0)) {
			auditLogCacheModel.stackTraceHash = null;
		}

		return auditLogCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(55);

		sb.append("{auditLogId=");
		sb.append(getAuditLogId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", courseCode=");
		sb.append(getCourseCode());
		sb.append(", ntucDTId=");
		sb.append(getNtucDTId());
		sb.append(", startTimeMs=");
		sb.append(getStartTimeMs());
		sb.append(", endTimeMs=");
		sb.append(getEndTimeMs());
		sb.append(", durationMs=");
		sb.append(getDurationMs());
		sb.append(", correlationId=");
		sb.append(getCorrelationId());
		sb.append(", jobRunId=");
		sb.append(getJobRunId());
		sb.append(", requestId=");
		sb.append(getRequestId());
		sb.append(", eventId=");
		sb.append(getEventId());
		sb.append(", severity=");
		sb.append(getSeverity());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append(", step=");
		sb.append(getStep());
		sb.append(", category=");
		sb.append(getCategory());
		sb.append(", message=");
		sb.append(getMessage());
		sb.append(", errorCode=");
		sb.append(getErrorCode());
		sb.append(", errorMessage=");
		sb.append(getErrorMessage());
		sb.append(", exceptionClass=");
		sb.append(getExceptionClass());
		sb.append(", alertFingerprint=");
		sb.append(getAlertFingerprint());
		sb.append(", stackTraceHash=");
		sb.append(getStackTraceHash());

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(85);

		sb.append("<model><model-name>");
		sb.append("com.ntuc.notification.model.AuditLog");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>auditLogId</column-name><column-value><![CDATA[");
		sb.append(getAuditLogId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>courseCode</column-name><column-value><![CDATA[");
		sb.append(getCourseCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ntucDTId</column-name><column-value><![CDATA[");
		sb.append(getNtucDTId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>startTimeMs</column-name><column-value><![CDATA[");
		sb.append(getStartTimeMs());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endTimeMs</column-name><column-value><![CDATA[");
		sb.append(getEndTimeMs());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>durationMs</column-name><column-value><![CDATA[");
		sb.append(getDurationMs());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>correlationId</column-name><column-value><![CDATA[");
		sb.append(getCorrelationId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>jobRunId</column-name><column-value><![CDATA[");
		sb.append(getJobRunId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>requestId</column-name><column-value><![CDATA[");
		sb.append(getRequestId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>eventId</column-name><column-value><![CDATA[");
		sb.append(getEventId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>severity</column-name><column-value><![CDATA[");
		sb.append(getSeverity());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>step</column-name><column-value><![CDATA[");
		sb.append(getStep());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>category</column-name><column-value><![CDATA[");
		sb.append(getCategory());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>message</column-name><column-value><![CDATA[");
		sb.append(getMessage());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>errorCode</column-name><column-value><![CDATA[");
		sb.append(getErrorCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>errorMessage</column-name><column-value><![CDATA[");
		sb.append(getErrorMessage());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>exceptionClass</column-name><column-value><![CDATA[");
		sb.append(getExceptionClass());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>alertFingerprint</column-name><column-value><![CDATA[");
		sb.append(getAlertFingerprint());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>stackTraceHash</column-name><column-value><![CDATA[");
		sb.append(getStackTraceHash());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, AuditLog>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _auditLogId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _courseCode;
	private long _ntucDTId;
	private long _startTimeMs;
	private long _endTimeMs;
	private long _durationMs;
	private String _correlationId;
	private String _jobRunId;
	private String _requestId;
	private String _eventId;
	private String _severity;
	private String _status;
	private String _step;
	private String _category;
	private String _message;
	private String _errorCode;
	private String _errorMessage;
	private String _exceptionClass;
	private String _alertFingerprint;
	private String _stackTraceHash;
	private AuditLogStackTraceTruncatedBlobModel _stackTraceTruncatedBlobModel;
	private AuditLogDetailsJsonBlobModel _detailsJsonBlobModel;

	public <T> T getColumnValue(String columnName) {
		Function<AuditLog, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((AuditLog)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("auditLogId", _auditLogId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("courseCode", _courseCode);
		_columnOriginalValues.put("ntucDTId", _ntucDTId);
		_columnOriginalValues.put("startTimeMs", _startTimeMs);
		_columnOriginalValues.put("endTimeMs", _endTimeMs);
		_columnOriginalValues.put("durationMs", _durationMs);
		_columnOriginalValues.put("correlationId", _correlationId);
		_columnOriginalValues.put("jobRunId", _jobRunId);
		_columnOriginalValues.put("requestId", _requestId);
		_columnOriginalValues.put("eventId", _eventId);
		_columnOriginalValues.put("severity", _severity);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("step", _step);
		_columnOriginalValues.put("category", _category);
		_columnOriginalValues.put("message", _message);
		_columnOriginalValues.put("errorCode", _errorCode);
		_columnOriginalValues.put("errorMessage", _errorMessage);
		_columnOriginalValues.put("exceptionClass", _exceptionClass);
		_columnOriginalValues.put("alertFingerprint", _alertFingerprint);
		_columnOriginalValues.put("stackTraceHash", _stackTraceHash);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("auditLogId", 1L);

		columnBitmasks.put("createDate", 2L);

		columnBitmasks.put("modifiedDate", 4L);

		columnBitmasks.put("groupId", 8L);

		columnBitmasks.put("companyId", 16L);

		columnBitmasks.put("userId", 32L);

		columnBitmasks.put("courseCode", 64L);

		columnBitmasks.put("ntucDTId", 128L);

		columnBitmasks.put("startTimeMs", 256L);

		columnBitmasks.put("endTimeMs", 512L);

		columnBitmasks.put("durationMs", 1024L);

		columnBitmasks.put("correlationId", 2048L);

		columnBitmasks.put("jobRunId", 4096L);

		columnBitmasks.put("requestId", 8192L);

		columnBitmasks.put("eventId", 16384L);

		columnBitmasks.put("severity", 32768L);

		columnBitmasks.put("status", 65536L);

		columnBitmasks.put("step", 131072L);

		columnBitmasks.put("category", 262144L);

		columnBitmasks.put("message", 524288L);

		columnBitmasks.put("errorCode", 1048576L);

		columnBitmasks.put("errorMessage", 2097152L);

		columnBitmasks.put("exceptionClass", 4194304L);

		columnBitmasks.put("alertFingerprint", 8388608L);

		columnBitmasks.put("stackTraceHash", 16777216L);

		columnBitmasks.put("stackTraceTruncated", 33554432L);

		columnBitmasks.put("detailsJson", 67108864L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private AuditLog _escapedModel;

}