/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ntuc.notification.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import com.ntuc.notification.model.CourseSchedule;
import com.ntuc.notification.model.CourseScheduleModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CourseSchedule service. Represents a row in the &quot;ntuc_cschedule&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CourseScheduleModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CourseScheduleImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CourseScheduleImpl
 * @generated
 */
public class CourseScheduleModelImpl
	extends BaseModelImpl<CourseSchedule> implements CourseScheduleModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a course schedule model instance should use the <code>CourseSchedule</code> interface instead.
	 */
	public static final String TABLE_NAME = "ntuc_cschedule";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"courseScheduleId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"courseCode", Types.VARCHAR}, {"intakeNumber", Types.VARCHAR},
		{"startDate", Types.TIMESTAMP}, {"endDate", Types.TIMESTAMP},
		{"durationHours", Types.INTEGER}, {"durationMinutes", Types.INTEGER},
		{"availability", Types.INTEGER}, {"venue", Types.VARCHAR},
		{"description", Types.VARCHAR}, {"availablePax", Types.VARCHAR},
		{"availableWaitlist", Types.VARCHAR}, {"lxpBuyUrl", Types.VARCHAR},
		{"lxpRoiUrl", Types.VARCHAR}, {"importantNote", Types.VARCHAR},
		{"scheduleDownloadUrl", Types.VARCHAR}, {"errorCode", Types.VARCHAR},
		{"errorMessage", Types.VARCHAR}, {"rawJson", Types.VARCHAR},
		{"modifiedBy", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("courseScheduleId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("courseCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("intakeNumber", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("startDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("endDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("durationHours", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("durationMinutes", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("availability", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("venue", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("availablePax", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("availableWaitlist", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lxpBuyUrl", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lxpRoiUrl", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("importantNote", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("scheduleDownloadUrl", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("errorCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("errorMessage", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("rawJson", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("modifiedBy", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ntuc_cschedule (uuid_ VARCHAR(75) null,courseScheduleId LONG not null primary key,groupId LONG,companyId LONG,createDate DATE null,modifiedDate DATE null,courseCode VARCHAR(255) null,intakeNumber VARCHAR(255) null,startDate DATE null,endDate DATE null,durationHours INTEGER,durationMinutes INTEGER,availability INTEGER,venue VARCHAR(512) null,description VARCHAR(2000) null,availablePax VARCHAR(50) null,availableWaitlist VARCHAR(50) null,lxpBuyUrl VARCHAR(1024) null,lxpRoiUrl VARCHAR(1024) null,importantNote VARCHAR(2000) null,scheduleDownloadUrl VARCHAR(1024) null,errorCode VARCHAR(255) null,errorMessage VARCHAR(2000) null,rawJson STRING null,modifiedBy LONG)";

	public static final String TABLE_SQL_DROP = "drop table ntuc_cschedule";

	public static final String ORDER_BY_JPQL =
		" ORDER BY courseSchedule.courseScheduleId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ntuc_cschedule.courseScheduleId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long COURSECODE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)
	 */
	@Deprecated
	public static final long COURSESCHEDULEID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public CourseScheduleModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _courseScheduleId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCourseScheduleId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _courseScheduleId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CourseSchedule.class;
	}

	@Override
	public String getModelClassName() {
		return CourseSchedule.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CourseSchedule, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CourseSchedule, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CourseSchedule, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((CourseSchedule)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CourseSchedule, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CourseSchedule, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CourseSchedule)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CourseSchedule, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CourseSchedule, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, CourseSchedule>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			CourseSchedule.class.getClassLoader(), CourseSchedule.class,
			ModelWrapper.class);

		try {
			Constructor<CourseSchedule> constructor =
				(Constructor<CourseSchedule>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<CourseSchedule, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<CourseSchedule, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<CourseSchedule, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<CourseSchedule, Object>>();
		Map<String, BiConsumer<CourseSchedule, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<CourseSchedule, ?>>();

		attributeGetterFunctions.put("uuid", CourseSchedule::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<CourseSchedule, String>)CourseSchedule::setUuid);
		attributeGetterFunctions.put(
			"courseScheduleId", CourseSchedule::getCourseScheduleId);
		attributeSetterBiConsumers.put(
			"courseScheduleId",
			(BiConsumer<CourseSchedule, Long>)
				CourseSchedule::setCourseScheduleId);
		attributeGetterFunctions.put("groupId", CourseSchedule::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<CourseSchedule, Long>)CourseSchedule::setGroupId);
		attributeGetterFunctions.put("companyId", CourseSchedule::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<CourseSchedule, Long>)CourseSchedule::setCompanyId);
		attributeGetterFunctions.put(
			"createDate", CourseSchedule::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<CourseSchedule, Date>)CourseSchedule::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", CourseSchedule::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<CourseSchedule, Date>)CourseSchedule::setModifiedDate);
		attributeGetterFunctions.put(
			"courseCode", CourseSchedule::getCourseCode);
		attributeSetterBiConsumers.put(
			"courseCode",
			(BiConsumer<CourseSchedule, String>)CourseSchedule::setCourseCode);
		attributeGetterFunctions.put(
			"intakeNumber", CourseSchedule::getIntakeNumber);
		attributeSetterBiConsumers.put(
			"intakeNumber",
			(BiConsumer<CourseSchedule, String>)
				CourseSchedule::setIntakeNumber);
		attributeGetterFunctions.put("startDate", CourseSchedule::getStartDate);
		attributeSetterBiConsumers.put(
			"startDate",
			(BiConsumer<CourseSchedule, Date>)CourseSchedule::setStartDate);
		attributeGetterFunctions.put("endDate", CourseSchedule::getEndDate);
		attributeSetterBiConsumers.put(
			"endDate",
			(BiConsumer<CourseSchedule, Date>)CourseSchedule::setEndDate);
		attributeGetterFunctions.put(
			"durationHours", CourseSchedule::getDurationHours);
		attributeSetterBiConsumers.put(
			"durationHours",
			(BiConsumer<CourseSchedule, Integer>)
				CourseSchedule::setDurationHours);
		attributeGetterFunctions.put(
			"durationMinutes", CourseSchedule::getDurationMinutes);
		attributeSetterBiConsumers.put(
			"durationMinutes",
			(BiConsumer<CourseSchedule, Integer>)
				CourseSchedule::setDurationMinutes);
		attributeGetterFunctions.put(
			"availability", CourseSchedule::getAvailability);
		attributeSetterBiConsumers.put(
			"availability",
			(BiConsumer<CourseSchedule, Integer>)
				CourseSchedule::setAvailability);
		attributeGetterFunctions.put("venue", CourseSchedule::getVenue);
		attributeSetterBiConsumers.put(
			"venue",
			(BiConsumer<CourseSchedule, String>)CourseSchedule::setVenue);
		attributeGetterFunctions.put(
			"description", CourseSchedule::getDescription);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<CourseSchedule, String>)CourseSchedule::setDescription);
		attributeGetterFunctions.put(
			"availablePax", CourseSchedule::getAvailablePax);
		attributeSetterBiConsumers.put(
			"availablePax",
			(BiConsumer<CourseSchedule, String>)
				CourseSchedule::setAvailablePax);
		attributeGetterFunctions.put(
			"availableWaitlist", CourseSchedule::getAvailableWaitlist);
		attributeSetterBiConsumers.put(
			"availableWaitlist",
			(BiConsumer<CourseSchedule, String>)
				CourseSchedule::setAvailableWaitlist);
		attributeGetterFunctions.put("lxpBuyUrl", CourseSchedule::getLxpBuyUrl);
		attributeSetterBiConsumers.put(
			"lxpBuyUrl",
			(BiConsumer<CourseSchedule, String>)CourseSchedule::setLxpBuyUrl);
		attributeGetterFunctions.put("lxpRoiUrl", CourseSchedule::getLxpRoiUrl);
		attributeSetterBiConsumers.put(
			"lxpRoiUrl",
			(BiConsumer<CourseSchedule, String>)CourseSchedule::setLxpRoiUrl);
		attributeGetterFunctions.put(
			"importantNote", CourseSchedule::getImportantNote);
		attributeSetterBiConsumers.put(
			"importantNote",
			(BiConsumer<CourseSchedule, String>)
				CourseSchedule::setImportantNote);
		attributeGetterFunctions.put(
			"scheduleDownloadUrl", CourseSchedule::getScheduleDownloadUrl);
		attributeSetterBiConsumers.put(
			"scheduleDownloadUrl",
			(BiConsumer<CourseSchedule, String>)
				CourseSchedule::setScheduleDownloadUrl);
		attributeGetterFunctions.put("errorCode", CourseSchedule::getErrorCode);
		attributeSetterBiConsumers.put(
			"errorCode",
			(BiConsumer<CourseSchedule, String>)CourseSchedule::setErrorCode);
		attributeGetterFunctions.put(
			"errorMessage", CourseSchedule::getErrorMessage);
		attributeSetterBiConsumers.put(
			"errorMessage",
			(BiConsumer<CourseSchedule, String>)
				CourseSchedule::setErrorMessage);
		attributeGetterFunctions.put("rawJson", CourseSchedule::getRawJson);
		attributeSetterBiConsumers.put(
			"rawJson",
			(BiConsumer<CourseSchedule, String>)CourseSchedule::setRawJson);
		attributeGetterFunctions.put(
			"modifiedBy", CourseSchedule::getModifiedBy);
		attributeSetterBiConsumers.put(
			"modifiedBy",
			(BiConsumer<CourseSchedule, Long>)CourseSchedule::setModifiedBy);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getCourseScheduleId() {
		return _courseScheduleId;
	}

	@Override
	public void setCourseScheduleId(long courseScheduleId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_courseScheduleId = courseScheduleId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getCourseCode() {
		if (_courseCode == null) {
			return "";
		}
		else {
			return _courseCode;
		}
	}

	@Override
	public void setCourseCode(String courseCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_courseCode = courseCode;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalCourseCode() {
		return getColumnOriginalValue("courseCode");
	}

	@Override
	public String getIntakeNumber() {
		if (_intakeNumber == null) {
			return "";
		}
		else {
			return _intakeNumber;
		}
	}

	@Override
	public void setIntakeNumber(String intakeNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_intakeNumber = intakeNumber;
	}

	@Override
	public Date getStartDate() {
		return _startDate;
	}

	@Override
	public void setStartDate(Date startDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_startDate = startDate;
	}

	@Override
	public Date getEndDate() {
		return _endDate;
	}

	@Override
	public void setEndDate(Date endDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_endDate = endDate;
	}

	@Override
	public int getDurationHours() {
		return _durationHours;
	}

	@Override
	public void setDurationHours(int durationHours) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_durationHours = durationHours;
	}

	@Override
	public int getDurationMinutes() {
		return _durationMinutes;
	}

	@Override
	public void setDurationMinutes(int durationMinutes) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_durationMinutes = durationMinutes;
	}

	@Override
	public int getAvailability() {
		return _availability;
	}

	@Override
	public void setAvailability(int availability) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_availability = availability;
	}

	@Override
	public String getVenue() {
		if (_venue == null) {
			return "";
		}
		else {
			return _venue;
		}
	}

	@Override
	public void setVenue(String venue) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_venue = venue;
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_description = description;
	}

	@Override
	public String getAvailablePax() {
		if (_availablePax == null) {
			return "";
		}
		else {
			return _availablePax;
		}
	}

	@Override
	public void setAvailablePax(String availablePax) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_availablePax = availablePax;
	}

	@Override
	public String getAvailableWaitlist() {
		if (_availableWaitlist == null) {
			return "";
		}
		else {
			return _availableWaitlist;
		}
	}

	@Override
	public void setAvailableWaitlist(String availableWaitlist) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_availableWaitlist = availableWaitlist;
	}

	@Override
	public String getLxpBuyUrl() {
		if (_lxpBuyUrl == null) {
			return "";
		}
		else {
			return _lxpBuyUrl;
		}
	}

	@Override
	public void setLxpBuyUrl(String lxpBuyUrl) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lxpBuyUrl = lxpBuyUrl;
	}

	@Override
	public String getLxpRoiUrl() {
		if (_lxpRoiUrl == null) {
			return "";
		}
		else {
			return _lxpRoiUrl;
		}
	}

	@Override
	public void setLxpRoiUrl(String lxpRoiUrl) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lxpRoiUrl = lxpRoiUrl;
	}

	@Override
	public String getImportantNote() {
		if (_importantNote == null) {
			return "";
		}
		else {
			return _importantNote;
		}
	}

	@Override
	public void setImportantNote(String importantNote) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_importantNote = importantNote;
	}

	@Override
	public String getScheduleDownloadUrl() {
		if (_scheduleDownloadUrl == null) {
			return "";
		}
		else {
			return _scheduleDownloadUrl;
		}
	}

	@Override
	public void setScheduleDownloadUrl(String scheduleDownloadUrl) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_scheduleDownloadUrl = scheduleDownloadUrl;
	}

	@Override
	public String getErrorCode() {
		if (_errorCode == null) {
			return "";
		}
		else {
			return _errorCode;
		}
	}

	@Override
	public void setErrorCode(String errorCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_errorCode = errorCode;
	}

	@Override
	public String getErrorMessage() {
		if (_errorMessage == null) {
			return "";
		}
		else {
			return _errorMessage;
		}
	}

	@Override
	public void setErrorMessage(String errorMessage) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_errorMessage = errorMessage;
	}

	@Override
	public String getRawJson() {
		if (_rawJson == null) {
			return "";
		}
		else {
			return _rawJson;
		}
	}

	@Override
	public void setRawJson(String rawJson) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_rawJson = rawJson;
	}

	@Override
	public long getModifiedBy() {
		return _modifiedBy;
	}

	@Override
	public void setModifiedBy(long modifiedBy) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedBy = modifiedBy;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(CourseSchedule.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (entry.getValue() != getColumnValue(entry.getKey())) {
				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), CourseSchedule.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CourseSchedule toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CourseSchedule>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CourseScheduleImpl courseScheduleImpl = new CourseScheduleImpl();

		courseScheduleImpl.setUuid(getUuid());
		courseScheduleImpl.setCourseScheduleId(getCourseScheduleId());
		courseScheduleImpl.setGroupId(getGroupId());
		courseScheduleImpl.setCompanyId(getCompanyId());
		courseScheduleImpl.setCreateDate(getCreateDate());
		courseScheduleImpl.setModifiedDate(getModifiedDate());
		courseScheduleImpl.setCourseCode(getCourseCode());
		courseScheduleImpl.setIntakeNumber(getIntakeNumber());
		courseScheduleImpl.setStartDate(getStartDate());
		courseScheduleImpl.setEndDate(getEndDate());
		courseScheduleImpl.setDurationHours(getDurationHours());
		courseScheduleImpl.setDurationMinutes(getDurationMinutes());
		courseScheduleImpl.setAvailability(getAvailability());
		courseScheduleImpl.setVenue(getVenue());
		courseScheduleImpl.setDescription(getDescription());
		courseScheduleImpl.setAvailablePax(getAvailablePax());
		courseScheduleImpl.setAvailableWaitlist(getAvailableWaitlist());
		courseScheduleImpl.setLxpBuyUrl(getLxpBuyUrl());
		courseScheduleImpl.setLxpRoiUrl(getLxpRoiUrl());
		courseScheduleImpl.setImportantNote(getImportantNote());
		courseScheduleImpl.setScheduleDownloadUrl(getScheduleDownloadUrl());
		courseScheduleImpl.setErrorCode(getErrorCode());
		courseScheduleImpl.setErrorMessage(getErrorMessage());
		courseScheduleImpl.setRawJson(getRawJson());
		courseScheduleImpl.setModifiedBy(getModifiedBy());

		courseScheduleImpl.resetOriginalValues();

		return courseScheduleImpl;
	}

	@Override
	public int compareTo(CourseSchedule courseSchedule) {
		long primaryKey = courseSchedule.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof CourseSchedule)) {
			return false;
		}

		CourseSchedule courseSchedule = (CourseSchedule)object;

		long primaryKey = courseSchedule.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<CourseSchedule> toCacheModel() {
		CourseScheduleCacheModel courseScheduleCacheModel =
			new CourseScheduleCacheModel();

		courseScheduleCacheModel.uuid = getUuid();

		String uuid = courseScheduleCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			courseScheduleCacheModel.uuid = null;
		}

		courseScheduleCacheModel.courseScheduleId = getCourseScheduleId();

		courseScheduleCacheModel.groupId = getGroupId();

		courseScheduleCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			courseScheduleCacheModel.createDate = createDate.getTime();
		}
		else {
			courseScheduleCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			courseScheduleCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			courseScheduleCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		courseScheduleCacheModel.courseCode = getCourseCode();

		String courseCode = courseScheduleCacheModel.courseCode;

		if ((courseCode != null) && (courseCode.length() == 0)) {
			courseScheduleCacheModel.courseCode = null;
		}

		courseScheduleCacheModel.intakeNumber = getIntakeNumber();

		String intakeNumber = courseScheduleCacheModel.intakeNumber;

		if ((intakeNumber != null) && (intakeNumber.length() == 0)) {
			courseScheduleCacheModel.intakeNumber = null;
		}

		Date startDate = getStartDate();

		if (startDate != null) {
			courseScheduleCacheModel.startDate = startDate.getTime();
		}
		else {
			courseScheduleCacheModel.startDate = Long.MIN_VALUE;
		}

		Date endDate = getEndDate();

		if (endDate != null) {
			courseScheduleCacheModel.endDate = endDate.getTime();
		}
		else {
			courseScheduleCacheModel.endDate = Long.MIN_VALUE;
		}

		courseScheduleCacheModel.durationHours = getDurationHours();

		courseScheduleCacheModel.durationMinutes = getDurationMinutes();

		courseScheduleCacheModel.availability = getAvailability();

		courseScheduleCacheModel.venue = getVenue();

		String venue = courseScheduleCacheModel.venue;

		if ((venue != null) && (venue.length() == 0)) {
			courseScheduleCacheModel.venue = null;
		}

		courseScheduleCacheModel.description = getDescription();

		String description = courseScheduleCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			courseScheduleCacheModel.description = null;
		}

		courseScheduleCacheModel.availablePax = getAvailablePax();

		String availablePax = courseScheduleCacheModel.availablePax;

		if ((availablePax != null) && (availablePax.length() == 0)) {
			courseScheduleCacheModel.availablePax = null;
		}

		courseScheduleCacheModel.availableWaitlist = getAvailableWaitlist();

		String availableWaitlist = courseScheduleCacheModel.availableWaitlist;

		if ((availableWaitlist != null) && (availableWaitlist.length() == 0)) {
			courseScheduleCacheModel.availableWaitlist = null;
		}

		courseScheduleCacheModel.lxpBuyUrl = getLxpBuyUrl();

		String lxpBuyUrl = courseScheduleCacheModel.lxpBuyUrl;

		if ((lxpBuyUrl != null) && (lxpBuyUrl.length() == 0)) {
			courseScheduleCacheModel.lxpBuyUrl = null;
		}

		courseScheduleCacheModel.lxpRoiUrl = getLxpRoiUrl();

		String lxpRoiUrl = courseScheduleCacheModel.lxpRoiUrl;

		if ((lxpRoiUrl != null) && (lxpRoiUrl.length() == 0)) {
			courseScheduleCacheModel.lxpRoiUrl = null;
		}

		courseScheduleCacheModel.importantNote = getImportantNote();

		String importantNote = courseScheduleCacheModel.importantNote;

		if ((importantNote != null) && (importantNote.length() == 0)) {
			courseScheduleCacheModel.importantNote = null;
		}

		courseScheduleCacheModel.scheduleDownloadUrl = getScheduleDownloadUrl();

		String scheduleDownloadUrl =
			courseScheduleCacheModel.scheduleDownloadUrl;

		if ((scheduleDownloadUrl != null) &&
			(scheduleDownloadUrl.length() == 0)) {

			courseScheduleCacheModel.scheduleDownloadUrl = null;
		}

		courseScheduleCacheModel.errorCode = getErrorCode();

		String errorCode = courseScheduleCacheModel.errorCode;

		if ((errorCode != null) && (errorCode.length() == 0)) {
			courseScheduleCacheModel.errorCode = null;
		}

		courseScheduleCacheModel.errorMessage = getErrorMessage();

		String errorMessage = courseScheduleCacheModel.errorMessage;

		if ((errorMessage != null) && (errorMessage.length() == 0)) {
			courseScheduleCacheModel.errorMessage = null;
		}

		courseScheduleCacheModel.rawJson = getRawJson();

		String rawJson = courseScheduleCacheModel.rawJson;

		if ((rawJson != null) && (rawJson.length() == 0)) {
			courseScheduleCacheModel.rawJson = null;
		}

		courseScheduleCacheModel.modifiedBy = getModifiedBy();

		return courseScheduleCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CourseSchedule, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CourseSchedule, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CourseSchedule, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((CourseSchedule)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<CourseSchedule, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<CourseSchedule, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CourseSchedule, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((CourseSchedule)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, CourseSchedule>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private long _courseScheduleId;
	private long _groupId;
	private long _companyId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _courseCode;
	private String _intakeNumber;
	private Date _startDate;
	private Date _endDate;
	private int _durationHours;
	private int _durationMinutes;
	private int _availability;
	private String _venue;
	private String _description;
	private String _availablePax;
	private String _availableWaitlist;
	private String _lxpBuyUrl;
	private String _lxpRoiUrl;
	private String _importantNote;
	private String _scheduleDownloadUrl;
	private String _errorCode;
	private String _errorMessage;
	private String _rawJson;
	private long _modifiedBy;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<CourseSchedule, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((CourseSchedule)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("courseScheduleId", _courseScheduleId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("courseCode", _courseCode);
		_columnOriginalValues.put("intakeNumber", _intakeNumber);
		_columnOriginalValues.put("startDate", _startDate);
		_columnOriginalValues.put("endDate", _endDate);
		_columnOriginalValues.put("durationHours", _durationHours);
		_columnOriginalValues.put("durationMinutes", _durationMinutes);
		_columnOriginalValues.put("availability", _availability);
		_columnOriginalValues.put("venue", _venue);
		_columnOriginalValues.put("description", _description);
		_columnOriginalValues.put("availablePax", _availablePax);
		_columnOriginalValues.put("availableWaitlist", _availableWaitlist);
		_columnOriginalValues.put("lxpBuyUrl", _lxpBuyUrl);
		_columnOriginalValues.put("lxpRoiUrl", _lxpRoiUrl);
		_columnOriginalValues.put("importantNote", _importantNote);
		_columnOriginalValues.put("scheduleDownloadUrl", _scheduleDownloadUrl);
		_columnOriginalValues.put("errorCode", _errorCode);
		_columnOriginalValues.put("errorMessage", _errorMessage);
		_columnOriginalValues.put("rawJson", _rawJson);
		_columnOriginalValues.put("modifiedBy", _modifiedBy);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("courseScheduleId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("createDate", 16L);

		columnBitmasks.put("modifiedDate", 32L);

		columnBitmasks.put("courseCode", 64L);

		columnBitmasks.put("intakeNumber", 128L);

		columnBitmasks.put("startDate", 256L);

		columnBitmasks.put("endDate", 512L);

		columnBitmasks.put("durationHours", 1024L);

		columnBitmasks.put("durationMinutes", 2048L);

		columnBitmasks.put("availability", 4096L);

		columnBitmasks.put("venue", 8192L);

		columnBitmasks.put("description", 16384L);

		columnBitmasks.put("availablePax", 32768L);

		columnBitmasks.put("availableWaitlist", 65536L);

		columnBitmasks.put("lxpBuyUrl", 131072L);

		columnBitmasks.put("lxpRoiUrl", 262144L);

		columnBitmasks.put("importantNote", 524288L);

		columnBitmasks.put("scheduleDownloadUrl", 1048576L);

		columnBitmasks.put("errorCode", 2097152L);

		columnBitmasks.put("errorMessage", 4194304L);

		columnBitmasks.put("rawJson", 8388608L);

		columnBitmasks.put("modifiedBy", 16777216L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private CourseSchedule _escapedModel;

}