/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ntuc.notification.model.impl;

import com.ntuc.notification.model.NtucSB;
import com.ntuc.notification.service.NtucSBLocalServiceUtil;

/**
 * The extended model base implementation for the NtucSB service. Represents a row in the &quot;ntuc_service_dt_notification&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link NtucSBImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see NtucSBImpl
 * @see NtucSB
 * @generated
 */
public abstract class NtucSBBaseImpl extends NtucSBModelImpl implements NtucSB {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ntuc sb model instance should use the <code>NtucSB</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			NtucSBLocalServiceUtil.addNtucSB(this);
		}
		else {
			NtucSBLocalServiceUtil.updateNtucSB(this);
		}
	}

}