/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ntuc.notification.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import com.ntuc.notification.model.NtucSB;
import com.ntuc.notification.model.NtucSBModel;
import com.ntuc.notification.model.NtucSBSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the NtucSB service. Represents a row in the &quot;ntuc_service_dt_notification&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>NtucSBModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link NtucSBImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see NtucSBImpl
 * @generated
 */
@JSON(strict = true)
public class NtucSBModelImpl
	extends BaseModelImpl<NtucSB> implements NtucSBModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ntuc sb model instance should use the <code>NtucSB</code> interface instead.
	 */
	public static final String TABLE_NAME = "ntuc_service_dt_notification";

	public static final Object[][] TABLE_COLUMNS = {
		{"ntucDTId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"courseCode", Types.VARCHAR}, {"courseType", Types.VARCHAR},
		{"notificationDate", Types.TIMESTAMP}, {"systemDate", Types.TIMESTAMP},
		{"notificationId", Types.VARCHAR}, {"event", Types.VARCHAR},
		{"changeFrom", Types.VARCHAR}, {"processingStatus", Types.VARCHAR},
		{"courseStatus", Types.VARCHAR}, {"isCriticalProcessed", Types.BOOLEAN},
		{"isNonCriticalProcessed", Types.BOOLEAN},
		{"isCronProcessed", Types.BOOLEAN}, {"canRetry", Types.BOOLEAN},
		{"lastRetried", Types.TIMESTAMP}, {"totalRetries", Types.INTEGER},
		{"isRowLockFailed", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("ntucDTId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("courseCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("courseType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("notificationDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("systemDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("notificationId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("event", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("changeFrom", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("processingStatus", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("courseStatus", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("isCriticalProcessed", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("isNonCriticalProcessed", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("isCronProcessed", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("canRetry", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("lastRetried", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("totalRetries", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("isRowLockFailed", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ntuc_service_dt_notification (ntucDTId LONG not null primary key,companyId LONG,courseCode VARCHAR(75) null,courseType VARCHAR(75) null,notificationDate DATE null,systemDate DATE null,notificationId VARCHAR(75) null,event VARCHAR(75) null,changeFrom VARCHAR(75) null,processingStatus VARCHAR(75) null,courseStatus VARCHAR(75) null,isCriticalProcessed BOOLEAN,isNonCriticalProcessed BOOLEAN,isCronProcessed BOOLEAN,canRetry BOOLEAN,lastRetried DATE null,totalRetries INTEGER,isRowLockFailed BOOLEAN)";

	public static final String TABLE_SQL_DROP =
		"drop table ntuc_service_dt_notification";

	public static final String ORDER_BY_JPQL =
		" ORDER BY ntucSB.systemDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ntuc_service_dt_notification.systemDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long CHANGEFROM_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long COURSECODE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long EVENT_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long ISCRITICALPROCESSED_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long ISCRONPROCESSED_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long ISNONCRITICALPROCESSED_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long ISROWLOCKFAILED_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)
	 */
	@Deprecated
	public static final long SYSTEMDATE_COLUMN_BITMASK = 128L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static NtucSB toModel(NtucSBSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		NtucSB model = new NtucSBImpl();

		model.setNtucDTId(soapModel.getNtucDTId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setCourseCode(soapModel.getCourseCode());
		model.setCourseType(soapModel.getCourseType());
		model.setNotificationDate(soapModel.getNotificationDate());
		model.setSystemDate(soapModel.getSystemDate());
		model.setNotificationId(soapModel.getNotificationId());
		model.setEvent(soapModel.getEvent());
		model.setChangeFrom(soapModel.getChangeFrom());
		model.setProcessingStatus(soapModel.getProcessingStatus());
		model.setCourseStatus(soapModel.getCourseStatus());
		model.setIsCriticalProcessed(soapModel.isIsCriticalProcessed());
		model.setIsNonCriticalProcessed(soapModel.isIsNonCriticalProcessed());
		model.setIsCronProcessed(soapModel.isIsCronProcessed());
		model.setCanRetry(soapModel.isCanRetry());
		model.setLastRetried(soapModel.getLastRetried());
		model.setTotalRetries(soapModel.getTotalRetries());
		model.setIsRowLockFailed(soapModel.isIsRowLockFailed());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<NtucSB> toModels(NtucSBSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<NtucSB> models = new ArrayList<NtucSB>(soapModels.length);

		for (NtucSBSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public NtucSBModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _ntucDTId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setNtucDTId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _ntucDTId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return NtucSB.class;
	}

	@Override
	public String getModelClassName() {
		return NtucSB.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<NtucSB, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<NtucSB, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<NtucSB, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((NtucSB)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<NtucSB, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<NtucSB, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(NtucSB)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<NtucSB, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<NtucSB, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, NtucSB>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			NtucSB.class.getClassLoader(), NtucSB.class, ModelWrapper.class);

		try {
			Constructor<NtucSB> constructor =
				(Constructor<NtucSB>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<NtucSB, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<NtucSB, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<NtucSB, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<NtucSB, Object>>();
		Map<String, BiConsumer<NtucSB, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<NtucSB, ?>>();

		attributeGetterFunctions.put("ntucDTId", NtucSB::getNtucDTId);
		attributeSetterBiConsumers.put(
			"ntucDTId", (BiConsumer<NtucSB, Long>)NtucSB::setNtucDTId);
		attributeGetterFunctions.put("companyId", NtucSB::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<NtucSB, Long>)NtucSB::setCompanyId);
		attributeGetterFunctions.put("courseCode", NtucSB::getCourseCode);
		attributeSetterBiConsumers.put(
			"courseCode", (BiConsumer<NtucSB, String>)NtucSB::setCourseCode);
		attributeGetterFunctions.put("courseType", NtucSB::getCourseType);
		attributeSetterBiConsumers.put(
			"courseType", (BiConsumer<NtucSB, String>)NtucSB::setCourseType);
		attributeGetterFunctions.put(
			"notificationDate", NtucSB::getNotificationDate);
		attributeSetterBiConsumers.put(
			"notificationDate",
			(BiConsumer<NtucSB, Date>)NtucSB::setNotificationDate);
		attributeGetterFunctions.put("systemDate", NtucSB::getSystemDate);
		attributeSetterBiConsumers.put(
			"systemDate", (BiConsumer<NtucSB, Date>)NtucSB::setSystemDate);
		attributeGetterFunctions.put(
			"notificationId", NtucSB::getNotificationId);
		attributeSetterBiConsumers.put(
			"notificationId",
			(BiConsumer<NtucSB, String>)NtucSB::setNotificationId);
		attributeGetterFunctions.put("event", NtucSB::getEvent);
		attributeSetterBiConsumers.put(
			"event", (BiConsumer<NtucSB, String>)NtucSB::setEvent);
		attributeGetterFunctions.put("changeFrom", NtucSB::getChangeFrom);
		attributeSetterBiConsumers.put(
			"changeFrom", (BiConsumer<NtucSB, String>)NtucSB::setChangeFrom);
		attributeGetterFunctions.put(
			"processingStatus", NtucSB::getProcessingStatus);
		attributeSetterBiConsumers.put(
			"processingStatus",
			(BiConsumer<NtucSB, String>)NtucSB::setProcessingStatus);
		attributeGetterFunctions.put("courseStatus", NtucSB::getCourseStatus);
		attributeSetterBiConsumers.put(
			"courseStatus",
			(BiConsumer<NtucSB, String>)NtucSB::setCourseStatus);
		attributeGetterFunctions.put(
			"isCriticalProcessed", NtucSB::getIsCriticalProcessed);
		attributeSetterBiConsumers.put(
			"isCriticalProcessed",
			(BiConsumer<NtucSB, Boolean>)NtucSB::setIsCriticalProcessed);
		attributeGetterFunctions.put(
			"isNonCriticalProcessed", NtucSB::getIsNonCriticalProcessed);
		attributeSetterBiConsumers.put(
			"isNonCriticalProcessed",
			(BiConsumer<NtucSB, Boolean>)NtucSB::setIsNonCriticalProcessed);
		attributeGetterFunctions.put(
			"isCronProcessed", NtucSB::getIsCronProcessed);
		attributeSetterBiConsumers.put(
			"isCronProcessed",
			(BiConsumer<NtucSB, Boolean>)NtucSB::setIsCronProcessed);
		attributeGetterFunctions.put("canRetry", NtucSB::getCanRetry);
		attributeSetterBiConsumers.put(
			"canRetry", (BiConsumer<NtucSB, Boolean>)NtucSB::setCanRetry);
		attributeGetterFunctions.put("lastRetried", NtucSB::getLastRetried);
		attributeSetterBiConsumers.put(
			"lastRetried", (BiConsumer<NtucSB, Date>)NtucSB::setLastRetried);
		attributeGetterFunctions.put("totalRetries", NtucSB::getTotalRetries);
		attributeSetterBiConsumers.put(
			"totalRetries",
			(BiConsumer<NtucSB, Integer>)NtucSB::setTotalRetries);
		attributeGetterFunctions.put(
			"isRowLockFailed", NtucSB::getIsRowLockFailed);
		attributeSetterBiConsumers.put(
			"isRowLockFailed",
			(BiConsumer<NtucSB, Boolean>)NtucSB::setIsRowLockFailed);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getNtucDTId() {
		return _ntucDTId;
	}

	@Override
	public void setNtucDTId(long ntucDTId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ntucDTId = ntucDTId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public String getCourseCode() {
		if (_courseCode == null) {
			return "";
		}
		else {
			return _courseCode;
		}
	}

	@Override
	public void setCourseCode(String courseCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_courseCode = courseCode;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalCourseCode() {
		return getColumnOriginalValue("courseCode");
	}

	@JSON
	@Override
	public String getCourseType() {
		if (_courseType == null) {
			return "";
		}
		else {
			return _courseType;
		}
	}

	@Override
	public void setCourseType(String courseType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_courseType = courseType;
	}

	@JSON
	@Override
	public Date getNotificationDate() {
		return _notificationDate;
	}

	@Override
	public void setNotificationDate(Date notificationDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_notificationDate = notificationDate;
	}

	@JSON
	@Override
	public Date getSystemDate() {
		return _systemDate;
	}

	@Override
	public void setSystemDate(Date systemDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_systemDate = systemDate;
	}

	@JSON
	@Override
	public String getNotificationId() {
		if (_notificationId == null) {
			return "";
		}
		else {
			return _notificationId;
		}
	}

	@Override
	public void setNotificationId(String notificationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_notificationId = notificationId;
	}

	@JSON
	@Override
	public String getEvent() {
		if (_event == null) {
			return "";
		}
		else {
			return _event;
		}
	}

	@Override
	public void setEvent(String event) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_event = event;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalEvent() {
		return getColumnOriginalValue("event");
	}

	@JSON
	@Override
	public String getChangeFrom() {
		if (_changeFrom == null) {
			return "";
		}
		else {
			return _changeFrom;
		}
	}

	@Override
	public void setChangeFrom(String changeFrom) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_changeFrom = changeFrom;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalChangeFrom() {
		return getColumnOriginalValue("changeFrom");
	}

	@JSON
	@Override
	public String getProcessingStatus() {
		if (_processingStatus == null) {
			return "";
		}
		else {
			return _processingStatus;
		}
	}

	@Override
	public void setProcessingStatus(String processingStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_processingStatus = processingStatus;
	}

	@JSON
	@Override
	public String getCourseStatus() {
		if (_courseStatus == null) {
			return "";
		}
		else {
			return _courseStatus;
		}
	}

	@Override
	public void setCourseStatus(String courseStatus) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_courseStatus = courseStatus;
	}

	@JSON
	@Override
	public boolean getIsCriticalProcessed() {
		return _isCriticalProcessed;
	}

	@JSON
	@Override
	public boolean isIsCriticalProcessed() {
		return _isCriticalProcessed;
	}

	@Override
	public void setIsCriticalProcessed(boolean isCriticalProcessed) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isCriticalProcessed = isCriticalProcessed;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public boolean getOriginalIsCriticalProcessed() {
		return GetterUtil.getBoolean(
			this.<Boolean>getColumnOriginalValue("isCriticalProcessed"));
	}

	@JSON
	@Override
	public boolean getIsNonCriticalProcessed() {
		return _isNonCriticalProcessed;
	}

	@JSON
	@Override
	public boolean isIsNonCriticalProcessed() {
		return _isNonCriticalProcessed;
	}

	@Override
	public void setIsNonCriticalProcessed(boolean isNonCriticalProcessed) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isNonCriticalProcessed = isNonCriticalProcessed;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public boolean getOriginalIsNonCriticalProcessed() {
		return GetterUtil.getBoolean(
			this.<Boolean>getColumnOriginalValue("isNonCriticalProcessed"));
	}

	@JSON
	@Override
	public boolean getIsCronProcessed() {
		return _isCronProcessed;
	}

	@JSON
	@Override
	public boolean isIsCronProcessed() {
		return _isCronProcessed;
	}

	@Override
	public void setIsCronProcessed(boolean isCronProcessed) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isCronProcessed = isCronProcessed;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public boolean getOriginalIsCronProcessed() {
		return GetterUtil.getBoolean(
			this.<Boolean>getColumnOriginalValue("isCronProcessed"));
	}

	@JSON
	@Override
	public boolean getCanRetry() {
		return _canRetry;
	}

	@JSON
	@Override
	public boolean isCanRetry() {
		return _canRetry;
	}

	@Override
	public void setCanRetry(boolean canRetry) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_canRetry = canRetry;
	}

	@JSON
	@Override
	public Date getLastRetried() {
		return _lastRetried;
	}

	@Override
	public void setLastRetried(Date lastRetried) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lastRetried = lastRetried;
	}

	@JSON
	@Override
	public int getTotalRetries() {
		return _totalRetries;
	}

	@Override
	public void setTotalRetries(int totalRetries) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_totalRetries = totalRetries;
	}

	@JSON
	@Override
	public boolean getIsRowLockFailed() {
		return _isRowLockFailed;
	}

	@JSON
	@Override
	public boolean isIsRowLockFailed() {
		return _isRowLockFailed;
	}

	@Override
	public void setIsRowLockFailed(boolean isRowLockFailed) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isRowLockFailed = isRowLockFailed;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public boolean getOriginalIsRowLockFailed() {
		return GetterUtil.getBoolean(
			this.<Boolean>getColumnOriginalValue("isRowLockFailed"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (entry.getValue() != getColumnValue(entry.getKey())) {
				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), NtucSB.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public NtucSB toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, NtucSB>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		NtucSBImpl ntucSBImpl = new NtucSBImpl();

		ntucSBImpl.setNtucDTId(getNtucDTId());
		ntucSBImpl.setCompanyId(getCompanyId());
		ntucSBImpl.setCourseCode(getCourseCode());
		ntucSBImpl.setCourseType(getCourseType());
		ntucSBImpl.setNotificationDate(getNotificationDate());
		ntucSBImpl.setSystemDate(getSystemDate());
		ntucSBImpl.setNotificationId(getNotificationId());
		ntucSBImpl.setEvent(getEvent());
		ntucSBImpl.setChangeFrom(getChangeFrom());
		ntucSBImpl.setProcessingStatus(getProcessingStatus());
		ntucSBImpl.setCourseStatus(getCourseStatus());
		ntucSBImpl.setIsCriticalProcessed(isIsCriticalProcessed());
		ntucSBImpl.setIsNonCriticalProcessed(isIsNonCriticalProcessed());
		ntucSBImpl.setIsCronProcessed(isIsCronProcessed());
		ntucSBImpl.setCanRetry(isCanRetry());
		ntucSBImpl.setLastRetried(getLastRetried());
		ntucSBImpl.setTotalRetries(getTotalRetries());
		ntucSBImpl.setIsRowLockFailed(isIsRowLockFailed());

		ntucSBImpl.resetOriginalValues();

		return ntucSBImpl;
	}

	@Override
	public int compareTo(NtucSB ntucSB) {
		int value = 0;

		value = DateUtil.compareTo(getSystemDate(), ntucSB.getSystemDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof NtucSB)) {
			return false;
		}

		NtucSB ntucSB = (NtucSB)object;

		long primaryKey = ntucSB.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<NtucSB> toCacheModel() {
		NtucSBCacheModel ntucSBCacheModel = new NtucSBCacheModel();

		ntucSBCacheModel.ntucDTId = getNtucDTId();

		ntucSBCacheModel.companyId = getCompanyId();

		ntucSBCacheModel.courseCode = getCourseCode();

		String courseCode = ntucSBCacheModel.courseCode;

		if ((courseCode != null) && (courseCode.length() == 0)) {
			ntucSBCacheModel.courseCode = null;
		}

		ntucSBCacheModel.courseType = getCourseType();

		String courseType = ntucSBCacheModel.courseType;

		if ((courseType != null) && (courseType.length() == 0)) {
			ntucSBCacheModel.courseType = null;
		}

		Date notificationDate = getNotificationDate();

		if (notificationDate != null) {
			ntucSBCacheModel.notificationDate = notificationDate.getTime();
		}
		else {
			ntucSBCacheModel.notificationDate = Long.MIN_VALUE;
		}

		Date systemDate = getSystemDate();

		if (systemDate != null) {
			ntucSBCacheModel.systemDate = systemDate.getTime();
		}
		else {
			ntucSBCacheModel.systemDate = Long.MIN_VALUE;
		}

		ntucSBCacheModel.notificationId = getNotificationId();

		String notificationId = ntucSBCacheModel.notificationId;

		if ((notificationId != null) && (notificationId.length() == 0)) {
			ntucSBCacheModel.notificationId = null;
		}

		ntucSBCacheModel.event = getEvent();

		String event = ntucSBCacheModel.event;

		if ((event != null) && (event.length() == 0)) {
			ntucSBCacheModel.event = null;
		}

		ntucSBCacheModel.changeFrom = getChangeFrom();

		String changeFrom = ntucSBCacheModel.changeFrom;

		if ((changeFrom != null) && (changeFrom.length() == 0)) {
			ntucSBCacheModel.changeFrom = null;
		}

		ntucSBCacheModel.processingStatus = getProcessingStatus();

		String processingStatus = ntucSBCacheModel.processingStatus;

		if ((processingStatus != null) && (processingStatus.length() == 0)) {
			ntucSBCacheModel.processingStatus = null;
		}

		ntucSBCacheModel.courseStatus = getCourseStatus();

		String courseStatus = ntucSBCacheModel.courseStatus;

		if ((courseStatus != null) && (courseStatus.length() == 0)) {
			ntucSBCacheModel.courseStatus = null;
		}

		ntucSBCacheModel.isCriticalProcessed = isIsCriticalProcessed();

		ntucSBCacheModel.isNonCriticalProcessed = isIsNonCriticalProcessed();

		ntucSBCacheModel.isCronProcessed = isIsCronProcessed();

		ntucSBCacheModel.canRetry = isCanRetry();

		Date lastRetried = getLastRetried();

		if (lastRetried != null) {
			ntucSBCacheModel.lastRetried = lastRetried.getTime();
		}
		else {
			ntucSBCacheModel.lastRetried = Long.MIN_VALUE;
		}

		ntucSBCacheModel.totalRetries = getTotalRetries();

		ntucSBCacheModel.isRowLockFailed = isIsRowLockFailed();

		return ntucSBCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<NtucSB, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<NtucSB, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<NtucSB, Object> attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((NtucSB)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<NtucSB, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<NtucSB, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<NtucSB, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((NtucSB)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, NtucSB>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _ntucDTId;
	private long _companyId;
	private String _courseCode;
	private String _courseType;
	private Date _notificationDate;
	private Date _systemDate;
	private String _notificationId;
	private String _event;
	private String _changeFrom;
	private String _processingStatus;
	private String _courseStatus;
	private boolean _isCriticalProcessed;
	private boolean _isNonCriticalProcessed;
	private boolean _isCronProcessed;
	private boolean _canRetry;
	private Date _lastRetried;
	private int _totalRetries;
	private boolean _isRowLockFailed;

	public <T> T getColumnValue(String columnName) {
		Function<NtucSB, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((NtucSB)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("ntucDTId", _ntucDTId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("courseCode", _courseCode);
		_columnOriginalValues.put("courseType", _courseType);
		_columnOriginalValues.put("notificationDate", _notificationDate);
		_columnOriginalValues.put("systemDate", _systemDate);
		_columnOriginalValues.put("notificationId", _notificationId);
		_columnOriginalValues.put("event", _event);
		_columnOriginalValues.put("changeFrom", _changeFrom);
		_columnOriginalValues.put("processingStatus", _processingStatus);
		_columnOriginalValues.put("courseStatus", _courseStatus);
		_columnOriginalValues.put("isCriticalProcessed", _isCriticalProcessed);
		_columnOriginalValues.put(
			"isNonCriticalProcessed", _isNonCriticalProcessed);
		_columnOriginalValues.put("isCronProcessed", _isCronProcessed);
		_columnOriginalValues.put("canRetry", _canRetry);
		_columnOriginalValues.put("lastRetried", _lastRetried);
		_columnOriginalValues.put("totalRetries", _totalRetries);
		_columnOriginalValues.put("isRowLockFailed", _isRowLockFailed);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("ntucDTId", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("courseCode", 4L);

		columnBitmasks.put("courseType", 8L);

		columnBitmasks.put("notificationDate", 16L);

		columnBitmasks.put("systemDate", 32L);

		columnBitmasks.put("notificationId", 64L);

		columnBitmasks.put("event", 128L);

		columnBitmasks.put("changeFrom", 256L);

		columnBitmasks.put("processingStatus", 512L);

		columnBitmasks.put("courseStatus", 1024L);

		columnBitmasks.put("isCriticalProcessed", 2048L);

		columnBitmasks.put("isNonCriticalProcessed", 4096L);

		columnBitmasks.put("isCronProcessed", 8192L);

		columnBitmasks.put("canRetry", 16384L);

		columnBitmasks.put("lastRetried", 32768L);

		columnBitmasks.put("totalRetries", 65536L);

		columnBitmasks.put("isRowLockFailed", 131072L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private NtucSB _escapedModel;

}