/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package svc.ntuc.nlh.course.admin.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Course service. Represents a row in the &quot;ntuc_course&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>svc.ntuc.nlh.course.admin.model.impl.CourseModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>svc.ntuc.nlh.course.admin.model.impl.CourseImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Course
 * @generated
 */
@ProviderType
public interface CourseModel
	extends BaseModel<Course>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a course model instance should use the {@link Course} interface instead.
	 */

	/**
	 * Returns the primary key of this course.
	 *
	 * @return the primary key of this course
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this course.
	 *
	 * @param primaryKey the primary key of this course
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this course.
	 *
	 * @return the uuid of this course
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this course.
	 *
	 * @param uuid the uuid of this course
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the course ID of this course.
	 *
	 * @return the course ID of this course
	 */
	public long getCourseId();

	/**
	 * Sets the course ID of this course.
	 *
	 * @param courseId the course ID of this course
	 */
	public void setCourseId(long courseId);

	/**
	 * Returns the group ID of this course.
	 *
	 * @return the group ID of this course
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this course.
	 *
	 * @param groupId the group ID of this course
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this course.
	 *
	 * @return the company ID of this course
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this course.
	 *
	 * @param companyId the company ID of this course
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this course.
	 *
	 * @return the user ID of this course
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this course.
	 *
	 * @param userId the user ID of this course
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this course.
	 *
	 * @return the user uuid of this course
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this course.
	 *
	 * @param userUuid the user uuid of this course
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this course.
	 *
	 * @return the user name of this course
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this course.
	 *
	 * @param userName the user name of this course
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this course.
	 *
	 * @return the create date of this course
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this course.
	 *
	 * @param createDate the create date of this course
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this course.
	 *
	 * @return the modified date of this course
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this course.
	 *
	 * @param modifiedDate the modified date of this course
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the end date of this course.
	 *
	 * @return the end date of this course
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this course.
	 *
	 * @param endDate the end date of this course
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the venue of this course.
	 *
	 * @return the venue of this course
	 */
	@AutoEscape
	public String getVenue();

	/**
	 * Sets the venue of this course.
	 *
	 * @param venue the venue of this course
	 */
	public void setVenue(String venue);

	/**
	 * Returns the allow online payment of this course.
	 *
	 * @return the allow online payment of this course
	 */
	public boolean getAllowOnlinePayment();

	/**
	 * Returns <code>true</code> if this course is allow online payment.
	 *
	 * @return <code>true</code> if this course is allow online payment; <code>false</code> otherwise
	 */
	public boolean isAllowOnlinePayment();

	/**
	 * Sets whether this course is allow online payment.
	 *
	 * @param allowOnlinePayment the allow online payment of this course
	 */
	public void setAllowOnlinePayment(boolean allowOnlinePayment);

	/**
	 * Returns the course title of this course.
	 *
	 * @return the course title of this course
	 */
	@AutoEscape
	public String getCourseTitle();

	/**
	 * Sets the course title of this course.
	 *
	 * @param courseTitle the course title of this course
	 */
	public void setCourseTitle(String courseTitle);

	/**
	 * Returns the allow web registration of this course.
	 *
	 * @return the allow web registration of this course
	 */
	public boolean getAllowWebRegistration();

	/**
	 * Returns <code>true</code> if this course is allow web registration.
	 *
	 * @return <code>true</code> if this course is allow web registration; <code>false</code> otherwise
	 */
	public boolean isAllowWebRegistration();

	/**
	 * Sets whether this course is allow web registration.
	 *
	 * @param allowWebRegistration the allow web registration of this course
	 */
	public void setAllowWebRegistration(boolean allowWebRegistration);

	/**
	 * Returns the description of this course.
	 *
	 * @return the description of this course
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this course.
	 *
	 * @param description the description of this course
	 */
	public void setDescription(String description);

	/**
	 * Returns the availability of this course.
	 *
	 * @return the availability of this course
	 */
	public int getAvailability();

	/**
	 * Sets the availability of this course.
	 *
	 * @param availability the availability of this course
	 */
	public void setAvailability(int availability);

	/**
	 * Returns the batch ID of this course.
	 *
	 * @return the batch ID of this course
	 */
	@AutoEscape
	public String getBatchId();

	/**
	 * Sets the batch ID of this course.
	 *
	 * @param batchId the batch ID of this course
	 */
	public void setBatchId(String batchId);

	/**
	 * Returns the web expiry of this course.
	 *
	 * @return the web expiry of this course
	 */
	public Date getWebExpiry();

	/**
	 * Sets the web expiry of this course.
	 *
	 * @param webExpiry the web expiry of this course
	 */
	public void setWebExpiry(Date webExpiry);

	/**
	 * Returns the funded course flag of this course.
	 *
	 * @return the funded course flag of this course
	 */
	public boolean getFundedCourseFlag();

	/**
	 * Returns <code>true</code> if this course is funded course flag.
	 *
	 * @return <code>true</code> if this course is funded course flag; <code>false</code> otherwise
	 */
	public boolean isFundedCourseFlag();

	/**
	 * Sets whether this course is funded course flag.
	 *
	 * @param fundedCourseFlag the funded course flag of this course
	 */
	public void setFundedCourseFlag(boolean fundedCourseFlag);

	/**
	 * Returns the course code of this course.
	 *
	 * @return the course code of this course
	 */
	@AutoEscape
	public String getCourseCode();

	/**
	 * Sets the course code of this course.
	 *
	 * @param courseCode the course code of this course
	 */
	public void setCourseCode(String courseCode);

	/**
	 * Returns the course duration of this course.
	 *
	 * @return the course duration of this course
	 */
	public Double getCourseDuration();

	/**
	 * Sets the course duration of this course.
	 *
	 * @param courseDuration the course duration of this course
	 */
	public void setCourseDuration(Double courseDuration);

	/**
	 * Returns the course type of this course.
	 *
	 * @return the course type of this course
	 */
	@AutoEscape
	public String getCourseType();

	/**
	 * Sets the course type of this course.
	 *
	 * @param courseType the course type of this course
	 */
	public void setCourseType(String courseType);

	/**
	 * Returns the course fee of this course.
	 *
	 * @return the course fee of this course
	 */
	public Double getCourseFee();

	/**
	 * Sets the course fee of this course.
	 *
	 * @param courseFee the course fee of this course
	 */
	public void setCourseFee(Double courseFee);

	/**
	 * Returns the deleted of this course.
	 *
	 * @return the deleted of this course
	 */
	public boolean getDeleted();

	/**
	 * Returns <code>true</code> if this course is deleted.
	 *
	 * @return <code>true</code> if this course is deleted; <code>false</code> otherwise
	 */
	public boolean isDeleted();

	/**
	 * Sets whether this course is deleted.
	 *
	 * @param deleted the deleted of this course
	 */
	public void setDeleted(boolean deleted);

	/**
	 * Returns the status of this course.
	 *
	 * @return the status of this course
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this course.
	 *
	 * @param status the status of this course
	 */
	public void setStatus(String status);

	/**
	 * Returns the start date of this course.
	 *
	 * @return the start date of this course
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this course.
	 *
	 * @param startDate the start date of this course
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the updated of this course.
	 *
	 * @return the updated of this course
	 */
	public boolean getUpdated();

	/**
	 * Returns <code>true</code> if this course is updated.
	 *
	 * @return <code>true</code> if this course is updated; <code>false</code> otherwise
	 */
	public boolean isUpdated();

	/**
	 * Sets whether this course is updated.
	 *
	 * @param updated the updated of this course
	 */
	public void setUpdated(boolean updated);

	/**
	 * Returns the popular of this course.
	 *
	 * @return the popular of this course
	 */
	public boolean getPopular();

	/**
	 * Returns <code>true</code> if this course is popular.
	 *
	 * @return <code>true</code> if this course is popular; <code>false</code> otherwise
	 */
	public boolean isPopular();

	/**
	 * Sets whether this course is popular.
	 *
	 * @param popular the popular of this course
	 */
	public void setPopular(boolean popular);

}