create table CSchedule (
	uuid_ VARCHAR(75) null,
	courseScheduleId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	createDate DATE null,
	modifiedDate DATE null,
	courseCode VARCHAR(255) null,
	intakeNumber VARCHAR(255) null,
	startDate DATE null,
	endDate DATE null,
	durationHours INTEGER,
	durationMinutes INTEGER,
	availability INTEGER,
	venue VARCHAR(512) null,
	description VARCHAR(2000) null,
	availablePax VARCHAR(50) null,
	availableWaitlist VARCHAR(50) null,
	lxpBuyUrl VARCHAR(1024) null,
	lxpRoiUrl VARCHAR(1024) null,
	importantNote VARCHAR(2000) null,
	scheduleDownloadUrl VARCHAR(1024) null,
	errorCode VARCHAR(255) null,
	errorMessage VARCHAR(2000) null,
	rawJson STRING null
);

create table ntuc_audit_log (
	auditLogId LONG not null primary key,
	createDate DATE null,
	modifiedDate DATE null,
	groupId LONG,
	companyId LONG,
	userId LONG,
	courseCode VARCHAR(75) null,
	ntucDTId LONG,
	startTimeMs LONG,
	endTimeMs LONG,
	durationMs LONG,
	correlationId VARCHAR(75) null,
	jobRunId VARCHAR(75) null,
	requestId VARCHAR(75) null,
	eventId VARCHAR(75) null,
	severity VARCHAR(75) null,
	status VARCHAR(75) null,
	step VARCHAR(75) null,
	category VARCHAR(75) null,
	message VARCHAR(75) null,
	errorCode VARCHAR(75) null,
	errorMessage VARCHAR(75) null,
	exceptionClass VARCHAR(75) null,
	alertFingerprint VARCHAR(75) null,
	stackTraceHash VARCHAR(75) null,
	stackTraceTruncated BLOB,
	detailsJson BLOB
);

create table ntuc_cschedule (
	uuid_ VARCHAR(75) null,
	courseScheduleId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	createDate DATE null,
	modifiedDate DATE null,
	courseCode VARCHAR(255) null,
	intakeNumber VARCHAR(255) null,
	startDate DATE null,
	endDate DATE null,
	durationHours INTEGER,
	durationMinutes INTEGER,
	availability INTEGER,
	venue VARCHAR(512) null,
	description VARCHAR(2000) null,
	availablePax VARCHAR(50) null,
	availableWaitlist VARCHAR(50) null,
	lxpBuyUrl VARCHAR(1024) null,
	lxpRoiUrl VARCHAR(1024) null,
	importantNote VARCHAR(2000) null,
	scheduleDownloadUrl VARCHAR(1024) null,
	errorCode VARCHAR(255) null,
	errorMessage VARCHAR(2000) null,
	rawJson STRING null,
	modifiedBy LONG
);

create table ntuc_service_dt_notification (
	ntucDTId LONG not null primary key,
	companyId LONG,
	courseCode VARCHAR(75) null,
	courseType VARCHAR(75) null,
	notificationDate DATE null,
	systemDate DATE null,
	notificationId VARCHAR(75) null,
	event VARCHAR(75) null,
	changeFrom VARCHAR(75) null,
	processingStatus VARCHAR(75) null,
	courseStatus VARCHAR(75) null,
	isCriticalProcessed BOOLEAN,
	isNonCriticalProcessed BOOLEAN,
	isCronProcessed BOOLEAN,
	canRetry BOOLEAN,
	lastRetried DATE null,
	totalRetries INTEGER,
	isRowLockFailed BOOLEAN
);