/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package svc.ntuc.nlh.seo.bulkupload.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the NtucBulkUpload service. Represents a row in the &quot;ntuc_seo_NtucBulkUpload&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>svc.ntuc.nlh.seo.bulkupload.model.impl.NtucBulkUploadModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>svc.ntuc.nlh.seo.bulkupload.model.impl.NtucBulkUploadImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see NtucBulkUpload
 * @generated
 */
@ProviderType
public interface NtucBulkUploadModel
	extends BaseModel<NtucBulkUpload>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ntuc bulk upload model instance should use the {@link NtucBulkUpload} interface instead.
	 */

	/**
	 * Returns the primary key of this ntuc bulk upload.
	 *
	 * @return the primary key of this ntuc bulk upload
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ntuc bulk upload.
	 *
	 * @param primaryKey the primary key of this ntuc bulk upload
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this ntuc bulk upload.
	 *
	 * @return the uuid of this ntuc bulk upload
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this ntuc bulk upload.
	 *
	 * @param uuid the uuid of this ntuc bulk upload
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the ntuc bulk upload ID of this ntuc bulk upload.
	 *
	 * @return the ntuc bulk upload ID of this ntuc bulk upload
	 */
	public long getNtucBulkUploadId();

	/**
	 * Sets the ntuc bulk upload ID of this ntuc bulk upload.
	 *
	 * @param ntucBulkUploadId the ntuc bulk upload ID of this ntuc bulk upload
	 */
	public void setNtucBulkUploadId(long ntucBulkUploadId);

	/**
	 * Returns the group ID of this ntuc bulk upload.
	 *
	 * @return the group ID of this ntuc bulk upload
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this ntuc bulk upload.
	 *
	 * @param groupId the group ID of this ntuc bulk upload
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this ntuc bulk upload.
	 *
	 * @return the company ID of this ntuc bulk upload
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this ntuc bulk upload.
	 *
	 * @param companyId the company ID of this ntuc bulk upload
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this ntuc bulk upload.
	 *
	 * @return the user ID of this ntuc bulk upload
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this ntuc bulk upload.
	 *
	 * @param userId the user ID of this ntuc bulk upload
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this ntuc bulk upload.
	 *
	 * @return the user uuid of this ntuc bulk upload
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this ntuc bulk upload.
	 *
	 * @param userUuid the user uuid of this ntuc bulk upload
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this ntuc bulk upload.
	 *
	 * @return the user name of this ntuc bulk upload
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this ntuc bulk upload.
	 *
	 * @param userName the user name of this ntuc bulk upload
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this ntuc bulk upload.
	 *
	 * @return the create date of this ntuc bulk upload
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this ntuc bulk upload.
	 *
	 * @param createDate the create date of this ntuc bulk upload
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this ntuc bulk upload.
	 *
	 * @return the modified date of this ntuc bulk upload
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this ntuc bulk upload.
	 *
	 * @param modifiedDate the modified date of this ntuc bulk upload
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the file name of this ntuc bulk upload.
	 *
	 * @return the file name of this ntuc bulk upload
	 */
	@AutoEscape
	public String getFileName();

	/**
	 * Sets the file name of this ntuc bulk upload.
	 *
	 * @param fileName the file name of this ntuc bulk upload
	 */
	public void setFileName(String fileName);

	/**
	 * Returns the row data of this ntuc bulk upload.
	 *
	 * @return the row data of this ntuc bulk upload
	 */
	@AutoEscape
	public String getRowData();

	/**
	 * Sets the row data of this ntuc bulk upload.
	 *
	 * @param rowData the row data of this ntuc bulk upload
	 */
	public void setRowData(String rowData);

}