package com.ntuc.notification.rest;

import com.liferay.oauth2.provider.scope.RequiresScope;
import com.ntuc.notification.model.CourseEventList;
import com.ntuc.notification.rest.internal.dto.CourseRestDtos;
import com.ntuc.notification.rest.internal.processor.CourseRestProcessor;

import javax.ws.rs.Consumes;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;

import org.osgi.service.component.annotations.Component;
import org.osgi.service.component.annotations.Reference;
import org.osgi.service.jaxrs.whiteboard.JaxrsWhiteboardConstants;

/**
 * REST resource exposing CLS → DT5 course notification endpoints.
 *
 * <p><b>Purpose (Business)</b>:
 * Serves as the secure HTTP entry point for inbound course notification payloads
 * originating from CLS. This resource ensures that external systems can trigger
 * DT5 course workflows through a controlled and authenticated REST interface.</p>
 *
 * <p><b>Purpose (Technical)</b>:
 * - Acts strictly as a routing and boundary layer.
 * - Enforces OAuth2 scope-based access control.
 * - Delegates all processing to {@link CourseRestProcessor}.
 * - Maps processor outcomes directly to HTTP {@link Response} objects.</p>
 *
 * <p><b>Responsibilities</b>:
 * - URL mapping and HTTP method binding
 * - Content-type enforcement (JSON)
 * - Security scope declaration
 * - Dependency wiring</p>
 *
 * <p><b>Explicit Non-Responsibilities</b>:
 * - No business logic
 * - No validation rules
 * - No audit event creation
 * - No alerting or error interpretation</p>
 *
 * <p>All validation, auditing, error handling, and downstream effects
 * are handled by the processor and service layers.</p>
 *
 * @author @akshaygawande
 */
@Path("/notify")
@RequiresScope({"Course.REST.everything", "Course.REST.everything.write"})
@Component(
    property = {
        // Marks this class as a JAX-RS resource
        JaxrsWhiteboardConstants.JAX_RS_RESOURCE + "=true",

        // Binds this resource to the Course.REST JAX-RS application
        JaxrsWhiteboardConstants.JAX_RS_APPLICATION_SELECT + "=("
            + JaxrsWhiteboardConstants.JAX_RS_NAME + "=Course.REST)"
    },
    service = Object.class
)
public class CourseResource {

    /**
     * Processor responsible for executing all course-related REST workflows.
     *
     * <p>This resource performs no logic beyond delegation; the processor
     * encapsulates validation, auditing, persistence, and response semantics.</p>
     */
    @Reference
    private CourseRestProcessor courseRestProcessor;

    /**
     * Handles standard CLS course notification events.
     *
     * @param wrapper container holding one or more course events
     * @return HTTP response generated by the processor layer
     */
    @POST
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    public Response postCourse(CourseEventList wrapper) {
        return courseRestProcessor.postCourse(wrapper);
    }

    /**
     * Handles one-time bulk or historical course load requests.
     *
     * <p>Typically used for controlled backfill or recovery scenarios rather
     * than real-time event ingestion.</p>
     *
     * @param req one-time load request descriptor
     * @return HTTP response generated by the processor layer
     */
    @POST
    @Path("/oneTimeLoad")
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    public Response postOneTimeLoad(CourseRestDtos.OneTimeLoadRequest req) {
        return courseRestProcessor.postOneTimeLoad(req);
    }
}
