/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package svc.ntuc.nlh.seo.bulkupload.service.base;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Reference;

import svc.ntuc.nlh.seo.bulkupload.model.NtucBulkUpload;
import svc.ntuc.nlh.seo.bulkupload.service.NtucBulkUploadLocalService;
import svc.ntuc.nlh.seo.bulkupload.service.persistence.NtucBulkUploadPersistence;

/**
 * Provides the base implementation for the ntuc bulk upload local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link svc.ntuc.nlh.seo.bulkupload.service.impl.NtucBulkUploadLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see svc.ntuc.nlh.seo.bulkupload.service.impl.NtucBulkUploadLocalServiceImpl
 * @generated
 */
public abstract class NtucBulkUploadLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService, NtucBulkUploadLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>NtucBulkUploadLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>svc.ntuc.nlh.seo.bulkupload.service.NtucBulkUploadLocalServiceUtil</code>.
	 */

	/**
	 * Adds the ntuc bulk upload to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect NtucBulkUploadLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param ntucBulkUpload the ntuc bulk upload
	 * @return the ntuc bulk upload that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public NtucBulkUpload addNtucBulkUpload(NtucBulkUpload ntucBulkUpload) {
		ntucBulkUpload.setNew(true);

		return ntucBulkUploadPersistence.update(ntucBulkUpload);
	}

	/**
	 * Creates a new ntuc bulk upload with the primary key. Does not add the ntuc bulk upload to the database.
	 *
	 * @param ntucBulkUploadId the primary key for the new ntuc bulk upload
	 * @return the new ntuc bulk upload
	 */
	@Override
	@Transactional(enabled = false)
	public NtucBulkUpload createNtucBulkUpload(long ntucBulkUploadId) {
		return ntucBulkUploadPersistence.create(ntucBulkUploadId);
	}

	/**
	 * Deletes the ntuc bulk upload with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect NtucBulkUploadLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param ntucBulkUploadId the primary key of the ntuc bulk upload
	 * @return the ntuc bulk upload that was removed
	 * @throws PortalException if a ntuc bulk upload with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public NtucBulkUpload deleteNtucBulkUpload(long ntucBulkUploadId)
		throws PortalException {

		return ntucBulkUploadPersistence.remove(ntucBulkUploadId);
	}

	/**
	 * Deletes the ntuc bulk upload from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect NtucBulkUploadLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param ntucBulkUpload the ntuc bulk upload
	 * @return the ntuc bulk upload that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public NtucBulkUpload deleteNtucBulkUpload(NtucBulkUpload ntucBulkUpload) {
		return ntucBulkUploadPersistence.remove(ntucBulkUpload);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			NtucBulkUpload.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return ntucBulkUploadPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>svc.ntuc.nlh.seo.bulkupload.model.impl.NtucBulkUploadModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return ntucBulkUploadPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>svc.ntuc.nlh.seo.bulkupload.model.impl.NtucBulkUploadModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return ntucBulkUploadPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return ntucBulkUploadPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return ntucBulkUploadPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public NtucBulkUpload fetchNtucBulkUpload(long ntucBulkUploadId) {
		return ntucBulkUploadPersistence.fetchByPrimaryKey(ntucBulkUploadId);
	}

	/**
	 * Returns the ntuc bulk upload matching the UUID and group.
	 *
	 * @param uuid the ntuc bulk upload's UUID
	 * @param groupId the primary key of the group
	 * @return the matching ntuc bulk upload, or <code>null</code> if a matching ntuc bulk upload could not be found
	 */
	@Override
	public NtucBulkUpload fetchNtucBulkUploadByUuidAndGroupId(
		String uuid, long groupId) {

		return ntucBulkUploadPersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the ntuc bulk upload with the primary key.
	 *
	 * @param ntucBulkUploadId the primary key of the ntuc bulk upload
	 * @return the ntuc bulk upload
	 * @throws PortalException if a ntuc bulk upload with the primary key could not be found
	 */
	@Override
	public NtucBulkUpload getNtucBulkUpload(long ntucBulkUploadId)
		throws PortalException {

		return ntucBulkUploadPersistence.findByPrimaryKey(ntucBulkUploadId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(ntucBulkUploadLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(NtucBulkUpload.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("ntucBulkUploadId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			ntucBulkUploadLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(NtucBulkUpload.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"ntucBulkUploadId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(ntucBulkUploadLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(NtucBulkUpload.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("ntucBulkUploadId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod<NtucBulkUpload>() {

				@Override
				public void performAction(NtucBulkUpload ntucBulkUpload)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, ntucBulkUpload);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(NtucBulkUpload.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return ntucBulkUploadPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return ntucBulkUploadLocalService.deleteNtucBulkUpload(
			(NtucBulkUpload)persistedModel);
	}

	public BasePersistence<NtucBulkUpload> getBasePersistence() {
		return ntucBulkUploadPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return ntucBulkUploadPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the ntuc bulk uploads matching the UUID and company.
	 *
	 * @param uuid the UUID of the ntuc bulk uploads
	 * @param companyId the primary key of the company
	 * @return the matching ntuc bulk uploads, or an empty list if no matches were found
	 */
	@Override
	public List<NtucBulkUpload> getNtucBulkUploadsByUuidAndCompanyId(
		String uuid, long companyId) {

		return ntucBulkUploadPersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of ntuc bulk uploads matching the UUID and company.
	 *
	 * @param uuid the UUID of the ntuc bulk uploads
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of ntuc bulk uploads
	 * @param end the upper bound of the range of ntuc bulk uploads (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching ntuc bulk uploads, or an empty list if no matches were found
	 */
	@Override
	public List<NtucBulkUpload> getNtucBulkUploadsByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<NtucBulkUpload> orderByComparator) {

		return ntucBulkUploadPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the ntuc bulk upload matching the UUID and group.
	 *
	 * @param uuid the ntuc bulk upload's UUID
	 * @param groupId the primary key of the group
	 * @return the matching ntuc bulk upload
	 * @throws PortalException if a matching ntuc bulk upload could not be found
	 */
	@Override
	public NtucBulkUpload getNtucBulkUploadByUuidAndGroupId(
			String uuid, long groupId)
		throws PortalException {

		return ntucBulkUploadPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the ntuc bulk uploads.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>svc.ntuc.nlh.seo.bulkupload.model.impl.NtucBulkUploadModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of ntuc bulk uploads
	 * @param end the upper bound of the range of ntuc bulk uploads (not inclusive)
	 * @return the range of ntuc bulk uploads
	 */
	@Override
	public List<NtucBulkUpload> getNtucBulkUploads(int start, int end) {
		return ntucBulkUploadPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of ntuc bulk uploads.
	 *
	 * @return the number of ntuc bulk uploads
	 */
	@Override
	public int getNtucBulkUploadsCount() {
		return ntucBulkUploadPersistence.countAll();
	}

	/**
	 * Updates the ntuc bulk upload in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect NtucBulkUploadLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param ntucBulkUpload the ntuc bulk upload
	 * @return the ntuc bulk upload that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public NtucBulkUpload updateNtucBulkUpload(NtucBulkUpload ntucBulkUpload) {
		return ntucBulkUploadPersistence.update(ntucBulkUpload);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			NtucBulkUploadLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		ntucBulkUploadLocalService = (NtucBulkUploadLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return NtucBulkUploadLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return NtucBulkUpload.class;
	}

	protected String getModelClassName() {
		return NtucBulkUpload.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = ntucBulkUploadPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	protected NtucBulkUploadLocalService ntucBulkUploadLocalService;

	@Reference
	protected NtucBulkUploadPersistence ntucBulkUploadPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}