create table ntuc_course (
	uuid_ VARCHAR(75) null,
	courseId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	endDate DATE null,
	venue VARCHAR(2000) null,
	allowOnlinePayment BOOLEAN,
	courseTitle VARCHAR(2000) null,
	allowWebRegistration BOOLEAN,
	description TEXT null,
	availability INTEGER,
	batchId VARCHAR(75) null,
	webExpiry DATE null,
	fundedCourseFlag BOOLEAN,
	courseCode VARCHAR(75) null,
	courseDuration DOUBLE,
	courseType VARCHAR(75) null,
	courseFee DOUBLE,
	deleted BOOLEAN,
	status VARCHAR(75) null,
	startDate DATE null,
	updated BOOLEAN,
	popular BOOLEAN
);