/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package svc.ntuc.nlh.comments.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Comment service. Represents a row in the &quot;NTUC_COMMENT_Comment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>svc.ntuc.nlh.comments.model.impl.CommentModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>svc.ntuc.nlh.comments.model.impl.CommentImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Comment
 * @generated
 */
@ProviderType
public interface CommentModel
	extends BaseModel<Comment>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a comment model instance should use the {@link Comment} interface instead.
	 */

	/**
	 * Returns the primary key of this comment.
	 *
	 * @return the primary key of this comment
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this comment.
	 *
	 * @param primaryKey the primary key of this comment
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this comment.
	 *
	 * @return the uuid of this comment
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this comment.
	 *
	 * @param uuid the uuid of this comment
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the comment ID of this comment.
	 *
	 * @return the comment ID of this comment
	 */
	public long getCommentId();

	/**
	 * Sets the comment ID of this comment.
	 *
	 * @param commentId the comment ID of this comment
	 */
	public void setCommentId(long commentId);

	/**
	 * Returns the group ID of this comment.
	 *
	 * @return the group ID of this comment
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this comment.
	 *
	 * @param groupId the group ID of this comment
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this comment.
	 *
	 * @return the company ID of this comment
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this comment.
	 *
	 * @param companyId the company ID of this comment
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this comment.
	 *
	 * @return the user ID of this comment
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this comment.
	 *
	 * @param userId the user ID of this comment
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this comment.
	 *
	 * @return the user uuid of this comment
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this comment.
	 *
	 * @param userUuid the user uuid of this comment
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this comment.
	 *
	 * @return the user name of this comment
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this comment.
	 *
	 * @param userName the user name of this comment
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this comment.
	 *
	 * @return the create date of this comment
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this comment.
	 *
	 * @param createDate the create date of this comment
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this comment.
	 *
	 * @return the modified date of this comment
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this comment.
	 *
	 * @param modifiedDate the modified date of this comment
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the comment text of this comment.
	 *
	 * @return the comment text of this comment
	 */
	@AutoEscape
	public String getCommentText();

	/**
	 * Sets the comment text of this comment.
	 *
	 * @param commentText the comment text of this comment
	 */
	public void setCommentText(String commentText);

	/**
	 * Returns the comment name of this comment.
	 *
	 * @return the comment name of this comment
	 */
	@AutoEscape
	public String getCommentName();

	/**
	 * Sets the comment name of this comment.
	 *
	 * @param commentName the comment name of this comment
	 */
	public void setCommentName(String commentName);

	/**
	 * Returns the comment email of this comment.
	 *
	 * @return the comment email of this comment
	 */
	@AutoEscape
	public String getCommentEmail();

	/**
	 * Sets the comment email of this comment.
	 *
	 * @param commentEmail the comment email of this comment
	 */
	public void setCommentEmail(String commentEmail);

	/**
	 * Returns the comment option of this comment.
	 *
	 * @return the comment option of this comment
	 */
	public boolean getCommentOption();

	/**
	 * Returns <code>true</code> if this comment is comment option.
	 *
	 * @return <code>true</code> if this comment is comment option; <code>false</code> otherwise
	 */
	public boolean isCommentOption();

	/**
	 * Sets whether this comment is comment option.
	 *
	 * @param commentOption the comment option of this comment
	 */
	public void setCommentOption(boolean commentOption);

	/**
	 * Returns the comment status of this comment.
	 *
	 * @return the comment status of this comment
	 */
	public boolean getCommentStatus();

	/**
	 * Returns <code>true</code> if this comment is comment status.
	 *
	 * @return <code>true</code> if this comment is comment status; <code>false</code> otherwise
	 */
	public boolean isCommentStatus();

	/**
	 * Sets whether this comment is comment status.
	 *
	 * @param commentStatus the comment status of this comment
	 */
	public void setCommentStatus(boolean commentStatus);

}