/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package svc.ntuc.nlh.parameter.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Parameter service. Represents a row in the &quot;ntuc_parameter&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>svc.ntuc.nlh.parameter.model.impl.ParameterModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>svc.ntuc.nlh.parameter.model.impl.ParameterImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Parameter
 * @generated
 */
@ProviderType
public interface ParameterModel extends BaseModel<Parameter>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a parameter model instance should use the {@link Parameter} interface instead.
	 */

	/**
	 * Returns the primary key of this parameter.
	 *
	 * @return the primary key of this parameter
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this parameter.
	 *
	 * @param primaryKey the primary key of this parameter
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the parameter ID of this parameter.
	 *
	 * @return the parameter ID of this parameter
	 */
	public long getParameterId();

	/**
	 * Sets the parameter ID of this parameter.
	 *
	 * @param parameterId the parameter ID of this parameter
	 */
	public void setParameterId(long parameterId);

	/**
	 * Returns the group ID of this parameter.
	 *
	 * @return the group ID of this parameter
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this parameter.
	 *
	 * @param groupId the group ID of this parameter
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the parameter group ID of this parameter.
	 *
	 * @return the parameter group ID of this parameter
	 */
	public long getParameterGroupId();

	/**
	 * Sets the parameter group ID of this parameter.
	 *
	 * @param parameterGroupId the parameter group ID of this parameter
	 */
	public void setParameterGroupId(long parameterGroupId);

	/**
	 * Returns the company ID of this parameter.
	 *
	 * @return the company ID of this parameter
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this parameter.
	 *
	 * @param companyId the company ID of this parameter
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the created by of this parameter.
	 *
	 * @return the created by of this parameter
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this parameter.
	 *
	 * @param createdBy the created by of this parameter
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the created date of this parameter.
	 *
	 * @return the created date of this parameter
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this parameter.
	 *
	 * @param createdDate the created date of this parameter
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the modified by of this parameter.
	 *
	 * @return the modified by of this parameter
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this parameter.
	 *
	 * @param modifiedBy the modified by of this parameter
	 */
	public void setModifiedBy(long modifiedBy);

	/**
	 * Returns the modified date of this parameter.
	 *
	 * @return the modified date of this parameter
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this parameter.
	 *
	 * @param modifiedDate the modified date of this parameter
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the param code of this parameter.
	 *
	 * @return the param code of this parameter
	 */
	@AutoEscape
	public String getParamCode();

	/**
	 * Sets the param code of this parameter.
	 *
	 * @param paramCode the param code of this parameter
	 */
	public void setParamCode(String paramCode);

	/**
	 * Returns the param name of this parameter.
	 *
	 * @return the param name of this parameter
	 */
	@AutoEscape
	public String getParamName();

	/**
	 * Sets the param name of this parameter.
	 *
	 * @param paramName the param name of this parameter
	 */
	public void setParamName(String paramName);

	/**
	 * Returns the param value of this parameter.
	 *
	 * @return the param value of this parameter
	 */
	@AutoEscape
	public String getParamValue();

	/**
	 * Sets the param value of this parameter.
	 *
	 * @param paramValue the param value of this parameter
	 */
	public void setParamValue(String paramValue);

	/**
	 * Returns the description of this parameter.
	 *
	 * @return the description of this parameter
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this parameter.
	 *
	 * @param description the description of this parameter
	 */
	public void setDescription(String description);

	/**
	 * Returns the deleted of this parameter.
	 *
	 * @return the deleted of this parameter
	 */
	public Boolean getDeleted();

	/**
	 * Sets the deleted of this parameter.
	 *
	 * @param deleted the deleted of this parameter
	 */
	public void setDeleted(Boolean deleted);

}