/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package svc.ntuc.nlh.parameter.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ReservedParameter service. Represents a row in the &quot;ntuc_reserved_parameter&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>svc.ntuc.nlh.parameter.model.impl.ReservedParameterModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>svc.ntuc.nlh.parameter.model.impl.ReservedParameterImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ReservedParameter
 * @generated
 */
@ProviderType
public interface ReservedParameterModel
	extends BaseModel<ReservedParameter>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a reserved parameter model instance should use the {@link ReservedParameter} interface instead.
	 */

	/**
	 * Returns the primary key of this reserved parameter.
	 *
	 * @return the primary key of this reserved parameter
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this reserved parameter.
	 *
	 * @param primaryKey the primary key of this reserved parameter
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the reserved parameter ID of this reserved parameter.
	 *
	 * @return the reserved parameter ID of this reserved parameter
	 */
	public long getReservedParameterId();

	/**
	 * Sets the reserved parameter ID of this reserved parameter.
	 *
	 * @param reservedParameterId the reserved parameter ID of this reserved parameter
	 */
	public void setReservedParameterId(long reservedParameterId);

	/**
	 * Returns the group ID of this reserved parameter.
	 *
	 * @return the group ID of this reserved parameter
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this reserved parameter.
	 *
	 * @param groupId the group ID of this reserved parameter
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the parameter ID of this reserved parameter.
	 *
	 * @return the parameter ID of this reserved parameter
	 */
	public long getParameterId();

	/**
	 * Sets the parameter ID of this reserved parameter.
	 *
	 * @param parameterId the parameter ID of this reserved parameter
	 */
	public void setParameterId(long parameterId);

	/**
	 * Returns the parameter group ID of this reserved parameter.
	 *
	 * @return the parameter group ID of this reserved parameter
	 */
	public long getParameterGroupId();

	/**
	 * Sets the parameter group ID of this reserved parameter.
	 *
	 * @param parameterGroupId the parameter group ID of this reserved parameter
	 */
	public void setParameterGroupId(long parameterGroupId);

	/**
	 * Returns the company ID of this reserved parameter.
	 *
	 * @return the company ID of this reserved parameter
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this reserved parameter.
	 *
	 * @param companyId the company ID of this reserved parameter
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the created by of this reserved parameter.
	 *
	 * @return the created by of this reserved parameter
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this reserved parameter.
	 *
	 * @param createdBy the created by of this reserved parameter
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the created date of this reserved parameter.
	 *
	 * @return the created date of this reserved parameter
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this reserved parameter.
	 *
	 * @param createdDate the created date of this reserved parameter
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the modified by of this reserved parameter.
	 *
	 * @return the modified by of this reserved parameter
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this reserved parameter.
	 *
	 * @param modifiedBy the modified by of this reserved parameter
	 */
	public void setModifiedBy(long modifiedBy);

	/**
	 * Returns the modified date of this reserved parameter.
	 *
	 * @return the modified date of this reserved parameter
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this reserved parameter.
	 *
	 * @param modifiedDate the modified date of this reserved parameter
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the param code of this reserved parameter.
	 *
	 * @return the param code of this reserved parameter
	 */
	@AutoEscape
	public String getParamCode();

	/**
	 * Sets the param code of this reserved parameter.
	 *
	 * @param paramCode the param code of this reserved parameter
	 */
	public void setParamCode(String paramCode);

	/**
	 * Returns the reserved by of this reserved parameter.
	 *
	 * @return the reserved by of this reserved parameter
	 */
	@AutoEscape
	public String getReservedBy();

	/**
	 * Sets the reserved by of this reserved parameter.
	 *
	 * @param reservedBy the reserved by of this reserved parameter
	 */
	public void setReservedBy(String reservedBy);

}