/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ntuc.notification.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CourseSchedule service. Represents a row in the &quot;ntuc_cschedule&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ntuc.notification.model.impl.CourseScheduleModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ntuc.notification.model.impl.CourseScheduleImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CourseSchedule
 * @generated
 */
@ProviderType
public interface CourseScheduleModel
	extends BaseModel<CourseSchedule>, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a course schedule model instance should use the {@link CourseSchedule} interface instead.
	 */

	/**
	 * Returns the primary key of this course schedule.
	 *
	 * @return the primary key of this course schedule
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this course schedule.
	 *
	 * @param primaryKey the primary key of this course schedule
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this course schedule.
	 *
	 * @return the uuid of this course schedule
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this course schedule.
	 *
	 * @param uuid the uuid of this course schedule
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the course schedule ID of this course schedule.
	 *
	 * @return the course schedule ID of this course schedule
	 */
	public long getCourseScheduleId();

	/**
	 * Sets the course schedule ID of this course schedule.
	 *
	 * @param courseScheduleId the course schedule ID of this course schedule
	 */
	public void setCourseScheduleId(long courseScheduleId);

	/**
	 * Returns the group ID of this course schedule.
	 *
	 * @return the group ID of this course schedule
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this course schedule.
	 *
	 * @param groupId the group ID of this course schedule
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this course schedule.
	 *
	 * @return the company ID of this course schedule
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this course schedule.
	 *
	 * @param companyId the company ID of this course schedule
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this course schedule.
	 *
	 * @return the create date of this course schedule
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this course schedule.
	 *
	 * @param createDate the create date of this course schedule
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this course schedule.
	 *
	 * @return the modified date of this course schedule
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this course schedule.
	 *
	 * @param modifiedDate the modified date of this course schedule
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the course code of this course schedule.
	 *
	 * @return the course code of this course schedule
	 */
	@AutoEscape
	public String getCourseCode();

	/**
	 * Sets the course code of this course schedule.
	 *
	 * @param courseCode the course code of this course schedule
	 */
	public void setCourseCode(String courseCode);

	/**
	 * Returns the intake number of this course schedule.
	 *
	 * @return the intake number of this course schedule
	 */
	@AutoEscape
	public String getIntakeNumber();

	/**
	 * Sets the intake number of this course schedule.
	 *
	 * @param intakeNumber the intake number of this course schedule
	 */
	public void setIntakeNumber(String intakeNumber);

	/**
	 * Returns the start date of this course schedule.
	 *
	 * @return the start date of this course schedule
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this course schedule.
	 *
	 * @param startDate the start date of this course schedule
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the end date of this course schedule.
	 *
	 * @return the end date of this course schedule
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this course schedule.
	 *
	 * @param endDate the end date of this course schedule
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the duration hours of this course schedule.
	 *
	 * @return the duration hours of this course schedule
	 */
	public int getDurationHours();

	/**
	 * Sets the duration hours of this course schedule.
	 *
	 * @param durationHours the duration hours of this course schedule
	 */
	public void setDurationHours(int durationHours);

	/**
	 * Returns the duration minutes of this course schedule.
	 *
	 * @return the duration minutes of this course schedule
	 */
	public int getDurationMinutes();

	/**
	 * Sets the duration minutes of this course schedule.
	 *
	 * @param durationMinutes the duration minutes of this course schedule
	 */
	public void setDurationMinutes(int durationMinutes);

	/**
	 * Returns the availability of this course schedule.
	 *
	 * @return the availability of this course schedule
	 */
	public int getAvailability();

	/**
	 * Sets the availability of this course schedule.
	 *
	 * @param availability the availability of this course schedule
	 */
	public void setAvailability(int availability);

	/**
	 * Returns the venue of this course schedule.
	 *
	 * @return the venue of this course schedule
	 */
	@AutoEscape
	public String getVenue();

	/**
	 * Sets the venue of this course schedule.
	 *
	 * @param venue the venue of this course schedule
	 */
	public void setVenue(String venue);

	/**
	 * Returns the description of this course schedule.
	 *
	 * @return the description of this course schedule
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this course schedule.
	 *
	 * @param description the description of this course schedule
	 */
	public void setDescription(String description);

	/**
	 * Returns the available pax of this course schedule.
	 *
	 * @return the available pax of this course schedule
	 */
	@AutoEscape
	public String getAvailablePax();

	/**
	 * Sets the available pax of this course schedule.
	 *
	 * @param availablePax the available pax of this course schedule
	 */
	public void setAvailablePax(String availablePax);

	/**
	 * Returns the available waitlist of this course schedule.
	 *
	 * @return the available waitlist of this course schedule
	 */
	@AutoEscape
	public String getAvailableWaitlist();

	/**
	 * Sets the available waitlist of this course schedule.
	 *
	 * @param availableWaitlist the available waitlist of this course schedule
	 */
	public void setAvailableWaitlist(String availableWaitlist);

	/**
	 * Returns the lxp buy url of this course schedule.
	 *
	 * @return the lxp buy url of this course schedule
	 */
	@AutoEscape
	public String getLxpBuyUrl();

	/**
	 * Sets the lxp buy url of this course schedule.
	 *
	 * @param lxpBuyUrl the lxp buy url of this course schedule
	 */
	public void setLxpBuyUrl(String lxpBuyUrl);

	/**
	 * Returns the lxp roi url of this course schedule.
	 *
	 * @return the lxp roi url of this course schedule
	 */
	@AutoEscape
	public String getLxpRoiUrl();

	/**
	 * Sets the lxp roi url of this course schedule.
	 *
	 * @param lxpRoiUrl the lxp roi url of this course schedule
	 */
	public void setLxpRoiUrl(String lxpRoiUrl);

	/**
	 * Returns the important note of this course schedule.
	 *
	 * @return the important note of this course schedule
	 */
	@AutoEscape
	public String getImportantNote();

	/**
	 * Sets the important note of this course schedule.
	 *
	 * @param importantNote the important note of this course schedule
	 */
	public void setImportantNote(String importantNote);

	/**
	 * Returns the schedule download url of this course schedule.
	 *
	 * @return the schedule download url of this course schedule
	 */
	@AutoEscape
	public String getScheduleDownloadUrl();

	/**
	 * Sets the schedule download url of this course schedule.
	 *
	 * @param scheduleDownloadUrl the schedule download url of this course schedule
	 */
	public void setScheduleDownloadUrl(String scheduleDownloadUrl);

	/**
	 * Returns the error code of this course schedule.
	 *
	 * @return the error code of this course schedule
	 */
	@AutoEscape
	public String getErrorCode();

	/**
	 * Sets the error code of this course schedule.
	 *
	 * @param errorCode the error code of this course schedule
	 */
	public void setErrorCode(String errorCode);

	/**
	 * Returns the error message of this course schedule.
	 *
	 * @return the error message of this course schedule
	 */
	@AutoEscape
	public String getErrorMessage();

	/**
	 * Sets the error message of this course schedule.
	 *
	 * @param errorMessage the error message of this course schedule
	 */
	public void setErrorMessage(String errorMessage);

	/**
	 * Returns the raw json of this course schedule.
	 *
	 * @return the raw json of this course schedule
	 */
	@AutoEscape
	public String getRawJson();

	/**
	 * Sets the raw json of this course schedule.
	 *
	 * @param rawJson the raw json of this course schedule
	 */
	public void setRawJson(String rawJson);

	/**
	 * Returns the modified by of this course schedule.
	 *
	 * @return the modified by of this course schedule
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this course schedule.
	 *
	 * @param modifiedBy the modified by of this course schedule
	 */
	public void setModifiedBy(long modifiedBy);

}