/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ntuc.notification.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the NtucSB service. Represents a row in the &quot;ntuc_service_dt_notification&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ntuc.notification.model.impl.NtucSBModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ntuc.notification.model.impl.NtucSBImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see NtucSB
 * @generated
 */
@ProviderType
public interface NtucSBModel extends BaseModel<NtucSB>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ntuc sb model instance should use the {@link NtucSB} interface instead.
	 */

	/**
	 * Returns the primary key of this ntuc sb.
	 *
	 * @return the primary key of this ntuc sb
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ntuc sb.
	 *
	 * @param primaryKey the primary key of this ntuc sb
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ntuc dt ID of this ntuc sb.
	 *
	 * @return the ntuc dt ID of this ntuc sb
	 */
	public long getNtucDTId();

	/**
	 * Sets the ntuc dt ID of this ntuc sb.
	 *
	 * @param ntucDTId the ntuc dt ID of this ntuc sb
	 */
	public void setNtucDTId(long ntucDTId);

	/**
	 * Returns the company ID of this ntuc sb.
	 *
	 * @return the company ID of this ntuc sb
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this ntuc sb.
	 *
	 * @param companyId the company ID of this ntuc sb
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the course code of this ntuc sb.
	 *
	 * @return the course code of this ntuc sb
	 */
	@AutoEscape
	public String getCourseCode();

	/**
	 * Sets the course code of this ntuc sb.
	 *
	 * @param courseCode the course code of this ntuc sb
	 */
	public void setCourseCode(String courseCode);

	/**
	 * Returns the course type of this ntuc sb.
	 *
	 * @return the course type of this ntuc sb
	 */
	@AutoEscape
	public String getCourseType();

	/**
	 * Sets the course type of this ntuc sb.
	 *
	 * @param courseType the course type of this ntuc sb
	 */
	public void setCourseType(String courseType);

	/**
	 * Returns the notification date of this ntuc sb.
	 *
	 * @return the notification date of this ntuc sb
	 */
	public Date getNotificationDate();

	/**
	 * Sets the notification date of this ntuc sb.
	 *
	 * @param notificationDate the notification date of this ntuc sb
	 */
	public void setNotificationDate(Date notificationDate);

	/**
	 * Returns the system date of this ntuc sb.
	 *
	 * @return the system date of this ntuc sb
	 */
	public Date getSystemDate();

	/**
	 * Sets the system date of this ntuc sb.
	 *
	 * @param systemDate the system date of this ntuc sb
	 */
	public void setSystemDate(Date systemDate);

	/**
	 * Returns the notification ID of this ntuc sb.
	 *
	 * @return the notification ID of this ntuc sb
	 */
	@AutoEscape
	public String getNotificationId();

	/**
	 * Sets the notification ID of this ntuc sb.
	 *
	 * @param notificationId the notification ID of this ntuc sb
	 */
	public void setNotificationId(String notificationId);

	/**
	 * Returns the event of this ntuc sb.
	 *
	 * @return the event of this ntuc sb
	 */
	@AutoEscape
	public String getEvent();

	/**
	 * Sets the event of this ntuc sb.
	 *
	 * @param event the event of this ntuc sb
	 */
	public void setEvent(String event);

	/**
	 * Returns the change from of this ntuc sb.
	 *
	 * @return the change from of this ntuc sb
	 */
	@AutoEscape
	public String getChangeFrom();

	/**
	 * Sets the change from of this ntuc sb.
	 *
	 * @param changeFrom the change from of this ntuc sb
	 */
	public void setChangeFrom(String changeFrom);

	/**
	 * Returns the processing status of this ntuc sb.
	 *
	 * @return the processing status of this ntuc sb
	 */
	@AutoEscape
	public String getProcessingStatus();

	/**
	 * Sets the processing status of this ntuc sb.
	 *
	 * @param processingStatus the processing status of this ntuc sb
	 */
	public void setProcessingStatus(String processingStatus);

	/**
	 * Returns the course status of this ntuc sb.
	 *
	 * @return the course status of this ntuc sb
	 */
	@AutoEscape
	public String getCourseStatus();

	/**
	 * Sets the course status of this ntuc sb.
	 *
	 * @param courseStatus the course status of this ntuc sb
	 */
	public void setCourseStatus(String courseStatus);

	/**
	 * Returns the is critical processed of this ntuc sb.
	 *
	 * @return the is critical processed of this ntuc sb
	 */
	public boolean getIsCriticalProcessed();

	/**
	 * Returns <code>true</code> if this ntuc sb is is critical processed.
	 *
	 * @return <code>true</code> if this ntuc sb is is critical processed; <code>false</code> otherwise
	 */
	public boolean isIsCriticalProcessed();

	/**
	 * Sets whether this ntuc sb is is critical processed.
	 *
	 * @param isCriticalProcessed the is critical processed of this ntuc sb
	 */
	public void setIsCriticalProcessed(boolean isCriticalProcessed);

	/**
	 * Returns the is non critical processed of this ntuc sb.
	 *
	 * @return the is non critical processed of this ntuc sb
	 */
	public boolean getIsNonCriticalProcessed();

	/**
	 * Returns <code>true</code> if this ntuc sb is is non critical processed.
	 *
	 * @return <code>true</code> if this ntuc sb is is non critical processed; <code>false</code> otherwise
	 */
	public boolean isIsNonCriticalProcessed();

	/**
	 * Sets whether this ntuc sb is is non critical processed.
	 *
	 * @param isNonCriticalProcessed the is non critical processed of this ntuc sb
	 */
	public void setIsNonCriticalProcessed(boolean isNonCriticalProcessed);

	/**
	 * Returns the is cron processed of this ntuc sb.
	 *
	 * @return the is cron processed of this ntuc sb
	 */
	public boolean getIsCronProcessed();

	/**
	 * Returns <code>true</code> if this ntuc sb is is cron processed.
	 *
	 * @return <code>true</code> if this ntuc sb is is cron processed; <code>false</code> otherwise
	 */
	public boolean isIsCronProcessed();

	/**
	 * Sets whether this ntuc sb is is cron processed.
	 *
	 * @param isCronProcessed the is cron processed of this ntuc sb
	 */
	public void setIsCronProcessed(boolean isCronProcessed);

	/**
	 * Returns the can retry of this ntuc sb.
	 *
	 * @return the can retry of this ntuc sb
	 */
	public boolean getCanRetry();

	/**
	 * Returns <code>true</code> if this ntuc sb is can retry.
	 *
	 * @return <code>true</code> if this ntuc sb is can retry; <code>false</code> otherwise
	 */
	public boolean isCanRetry();

	/**
	 * Sets whether this ntuc sb is can retry.
	 *
	 * @param canRetry the can retry of this ntuc sb
	 */
	public void setCanRetry(boolean canRetry);

	/**
	 * Returns the last retried of this ntuc sb.
	 *
	 * @return the last retried of this ntuc sb
	 */
	public Date getLastRetried();

	/**
	 * Sets the last retried of this ntuc sb.
	 *
	 * @param lastRetried the last retried of this ntuc sb
	 */
	public void setLastRetried(Date lastRetried);

	/**
	 * Returns the total retries of this ntuc sb.
	 *
	 * @return the total retries of this ntuc sb
	 */
	public int getTotalRetries();

	/**
	 * Sets the total retries of this ntuc sb.
	 *
	 * @param totalRetries the total retries of this ntuc sb
	 */
	public void setTotalRetries(int totalRetries);

	/**
	 * Returns the is row lock failed of this ntuc sb.
	 *
	 * @return the is row lock failed of this ntuc sb
	 */
	public boolean getIsRowLockFailed();

	/**
	 * Returns <code>true</code> if this ntuc sb is is row lock failed.
	 *
	 * @return <code>true</code> if this ntuc sb is is row lock failed; <code>false</code> otherwise
	 */
	public boolean isIsRowLockFailed();

	/**
	 * Sets whether this ntuc sb is is row lock failed.
	 *
	 * @param isRowLockFailed the is row lock failed of this ntuc sb
	 */
	public void setIsRowLockFailed(boolean isRowLockFailed);

}