/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package svc.ntuc.nlh.course.admin.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import svc.ntuc.nlh.course.admin.model.Course;
import svc.ntuc.nlh.course.admin.model.CourseModel;
import svc.ntuc.nlh.course.admin.model.CourseSoap;

/**
 * The base model implementation for the Course service. Represents a row in the &quot;ntuc_course&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CourseModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CourseImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CourseImpl
 * @generated
 */
@JSON(strict = true)
public class CourseModelImpl
	extends BaseModelImpl<Course> implements CourseModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a course model instance should use the <code>Course</code> interface instead.
	 */
	public static final String TABLE_NAME = "ntuc_course";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"courseId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"endDate", Types.TIMESTAMP}, {"venue", Types.VARCHAR},
		{"allowOnlinePayment", Types.BOOLEAN}, {"courseTitle", Types.VARCHAR},
		{"allowWebRegistration", Types.BOOLEAN}, {"description", Types.VARCHAR},
		{"availability", Types.INTEGER}, {"batchId", Types.VARCHAR},
		{"webExpiry", Types.TIMESTAMP}, {"fundedCourseFlag", Types.BOOLEAN},
		{"courseCode", Types.VARCHAR}, {"courseDuration", Types.DOUBLE},
		{"courseType", Types.VARCHAR}, {"courseFee", Types.DOUBLE},
		{"deleted", Types.BOOLEAN}, {"status", Types.VARCHAR},
		{"startDate", Types.TIMESTAMP}, {"updated", Types.BOOLEAN},
		{"popular", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("courseId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("endDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("venue", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("allowOnlinePayment", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("courseTitle", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("allowWebRegistration", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("availability", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("batchId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("webExpiry", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("fundedCourseFlag", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("courseCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("courseDuration", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("courseType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("courseFee", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("deleted", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("status", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("startDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("updated", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("popular", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ntuc_course (uuid_ VARCHAR(75) null,courseId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,endDate DATE null,venue VARCHAR(2000) null,allowOnlinePayment BOOLEAN,courseTitle VARCHAR(2000) null,allowWebRegistration BOOLEAN,description TEXT null,availability INTEGER,batchId VARCHAR(75) null,webExpiry DATE null,fundedCourseFlag BOOLEAN,courseCode VARCHAR(75) null,courseDuration DOUBLE,courseType VARCHAR(75) null,courseFee DOUBLE,deleted BOOLEAN,status VARCHAR(75) null,startDate DATE null,updated BOOLEAN,popular BOOLEAN)";

	public static final String TABLE_SQL_DROP = "drop table ntuc_course";

	public static final String ORDER_BY_JPQL = " ORDER BY course.startDate ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ntuc_course.startDate ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long BATCHID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long COURSECODE_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long COURSETITLE_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long DELETED_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long POPULAR_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long UPDATED_COLUMN_BITMASK = 128L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 256L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)
	 */
	@Deprecated
	public static final long STARTDATE_COLUMN_BITMASK = 512L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static Course toModel(CourseSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Course model = new CourseImpl();

		model.setUuid(soapModel.getUuid());
		model.setCourseId(soapModel.getCourseId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setEndDate(soapModel.getEndDate());
		model.setVenue(soapModel.getVenue());
		model.setAllowOnlinePayment(soapModel.isAllowOnlinePayment());
		model.setCourseTitle(soapModel.getCourseTitle());
		model.setAllowWebRegistration(soapModel.isAllowWebRegistration());
		model.setDescription(soapModel.getDescription());
		model.setAvailability(soapModel.getAvailability());
		model.setBatchId(soapModel.getBatchId());
		model.setWebExpiry(soapModel.getWebExpiry());
		model.setFundedCourseFlag(soapModel.isFundedCourseFlag());
		model.setCourseCode(soapModel.getCourseCode());
		model.setCourseDuration(soapModel.getCourseDuration());
		model.setCourseType(soapModel.getCourseType());
		model.setCourseFee(soapModel.getCourseFee());
		model.setDeleted(soapModel.isDeleted());
		model.setStatus(soapModel.getStatus());
		model.setStartDate(soapModel.getStartDate());
		model.setUpdated(soapModel.isUpdated());
		model.setPopular(soapModel.isPopular());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<Course> toModels(CourseSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Course> models = new ArrayList<Course>(soapModels.length);

		for (CourseSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public CourseModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _courseId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCourseId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _courseId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Course.class;
	}

	@Override
	public String getModelClassName() {
		return Course.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Course, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Course, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Course, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Course)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Course, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Course, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Course)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Course, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Course, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Course>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Course.class.getClassLoader(), Course.class, ModelWrapper.class);

		try {
			Constructor<Course> constructor =
				(Constructor<Course>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<Course, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Course, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Course, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Course, Object>>();
		Map<String, BiConsumer<Course, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Course, ?>>();

		attributeGetterFunctions.put("uuid", Course::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Course, String>)Course::setUuid);
		attributeGetterFunctions.put("courseId", Course::getCourseId);
		attributeSetterBiConsumers.put(
			"courseId", (BiConsumer<Course, Long>)Course::setCourseId);
		attributeGetterFunctions.put("groupId", Course::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Course, Long>)Course::setGroupId);
		attributeGetterFunctions.put("companyId", Course::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<Course, Long>)Course::setCompanyId);
		attributeGetterFunctions.put("userId", Course::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Course, Long>)Course::setUserId);
		attributeGetterFunctions.put("userName", Course::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<Course, String>)Course::setUserName);
		attributeGetterFunctions.put("createDate", Course::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<Course, Date>)Course::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", Course::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate", (BiConsumer<Course, Date>)Course::setModifiedDate);
		attributeGetterFunctions.put("endDate", Course::getEndDate);
		attributeSetterBiConsumers.put(
			"endDate", (BiConsumer<Course, Date>)Course::setEndDate);
		attributeGetterFunctions.put("venue", Course::getVenue);
		attributeSetterBiConsumers.put(
			"venue", (BiConsumer<Course, String>)Course::setVenue);
		attributeGetterFunctions.put(
			"allowOnlinePayment", Course::getAllowOnlinePayment);
		attributeSetterBiConsumers.put(
			"allowOnlinePayment",
			(BiConsumer<Course, Boolean>)Course::setAllowOnlinePayment);
		attributeGetterFunctions.put("courseTitle", Course::getCourseTitle);
		attributeSetterBiConsumers.put(
			"courseTitle", (BiConsumer<Course, String>)Course::setCourseTitle);
		attributeGetterFunctions.put(
			"allowWebRegistration", Course::getAllowWebRegistration);
		attributeSetterBiConsumers.put(
			"allowWebRegistration",
			(BiConsumer<Course, Boolean>)Course::setAllowWebRegistration);
		attributeGetterFunctions.put("description", Course::getDescription);
		attributeSetterBiConsumers.put(
			"description", (BiConsumer<Course, String>)Course::setDescription);
		attributeGetterFunctions.put("availability", Course::getAvailability);
		attributeSetterBiConsumers.put(
			"availability",
			(BiConsumer<Course, Integer>)Course::setAvailability);
		attributeGetterFunctions.put("batchId", Course::getBatchId);
		attributeSetterBiConsumers.put(
			"batchId", (BiConsumer<Course, String>)Course::setBatchId);
		attributeGetterFunctions.put("webExpiry", Course::getWebExpiry);
		attributeSetterBiConsumers.put(
			"webExpiry", (BiConsumer<Course, Date>)Course::setWebExpiry);
		attributeGetterFunctions.put(
			"fundedCourseFlag", Course::getFundedCourseFlag);
		attributeSetterBiConsumers.put(
			"fundedCourseFlag",
			(BiConsumer<Course, Boolean>)Course::setFundedCourseFlag);
		attributeGetterFunctions.put("courseCode", Course::getCourseCode);
		attributeSetterBiConsumers.put(
			"courseCode", (BiConsumer<Course, String>)Course::setCourseCode);
		attributeGetterFunctions.put(
			"courseDuration", Course::getCourseDuration);
		attributeSetterBiConsumers.put(
			"courseDuration",
			(BiConsumer<Course, Double>)Course::setCourseDuration);
		attributeGetterFunctions.put("courseType", Course::getCourseType);
		attributeSetterBiConsumers.put(
			"courseType", (BiConsumer<Course, String>)Course::setCourseType);
		attributeGetterFunctions.put("courseFee", Course::getCourseFee);
		attributeSetterBiConsumers.put(
			"courseFee", (BiConsumer<Course, Double>)Course::setCourseFee);
		attributeGetterFunctions.put("deleted", Course::getDeleted);
		attributeSetterBiConsumers.put(
			"deleted", (BiConsumer<Course, Boolean>)Course::setDeleted);
		attributeGetterFunctions.put("status", Course::getStatus);
		attributeSetterBiConsumers.put(
			"status", (BiConsumer<Course, String>)Course::setStatus);
		attributeGetterFunctions.put("startDate", Course::getStartDate);
		attributeSetterBiConsumers.put(
			"startDate", (BiConsumer<Course, Date>)Course::setStartDate);
		attributeGetterFunctions.put("updated", Course::getUpdated);
		attributeSetterBiConsumers.put(
			"updated", (BiConsumer<Course, Boolean>)Course::setUpdated);
		attributeGetterFunctions.put("popular", Course::getPopular);
		attributeSetterBiConsumers.put(
			"popular", (BiConsumer<Course, Boolean>)Course::setPopular);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getCourseId() {
		return _courseId;
	}

	@Override
	public void setCourseId(long courseId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_courseId = courseId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public Date getEndDate() {
		return _endDate;
	}

	@Override
	public void setEndDate(Date endDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_endDate = endDate;
	}

	@JSON
	@Override
	public String getVenue() {
		if (_venue == null) {
			return "";
		}
		else {
			return _venue;
		}
	}

	@Override
	public void setVenue(String venue) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_venue = venue;
	}

	@JSON
	@Override
	public boolean getAllowOnlinePayment() {
		return _allowOnlinePayment;
	}

	@JSON
	@Override
	public boolean isAllowOnlinePayment() {
		return _allowOnlinePayment;
	}

	@Override
	public void setAllowOnlinePayment(boolean allowOnlinePayment) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_allowOnlinePayment = allowOnlinePayment;
	}

	@JSON
	@Override
	public String getCourseTitle() {
		if (_courseTitle == null) {
			return "";
		}
		else {
			return _courseTitle;
		}
	}

	@Override
	public void setCourseTitle(String courseTitle) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_courseTitle = courseTitle;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalCourseTitle() {
		return getColumnOriginalValue("courseTitle");
	}

	@JSON
	@Override
	public boolean getAllowWebRegistration() {
		return _allowWebRegistration;
	}

	@JSON
	@Override
	public boolean isAllowWebRegistration() {
		return _allowWebRegistration;
	}

	@Override
	public void setAllowWebRegistration(boolean allowWebRegistration) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_allowWebRegistration = allowWebRegistration;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_description = description;
	}

	@JSON
	@Override
	public int getAvailability() {
		return _availability;
	}

	@Override
	public void setAvailability(int availability) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_availability = availability;
	}

	@JSON
	@Override
	public String getBatchId() {
		if (_batchId == null) {
			return "";
		}
		else {
			return _batchId;
		}
	}

	@Override
	public void setBatchId(String batchId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_batchId = batchId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalBatchId() {
		return getColumnOriginalValue("batchId");
	}

	@JSON
	@Override
	public Date getWebExpiry() {
		return _webExpiry;
	}

	@Override
	public void setWebExpiry(Date webExpiry) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_webExpiry = webExpiry;
	}

	@JSON
	@Override
	public boolean getFundedCourseFlag() {
		return _fundedCourseFlag;
	}

	@JSON
	@Override
	public boolean isFundedCourseFlag() {
		return _fundedCourseFlag;
	}

	@Override
	public void setFundedCourseFlag(boolean fundedCourseFlag) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fundedCourseFlag = fundedCourseFlag;
	}

	@JSON
	@Override
	public String getCourseCode() {
		if (_courseCode == null) {
			return "";
		}
		else {
			return _courseCode;
		}
	}

	@Override
	public void setCourseCode(String courseCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_courseCode = courseCode;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalCourseCode() {
		return getColumnOriginalValue("courseCode");
	}

	@JSON
	@Override
	public Double getCourseDuration() {
		return _courseDuration;
	}

	@Override
	public void setCourseDuration(Double courseDuration) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_courseDuration = courseDuration;
	}

	@JSON
	@Override
	public String getCourseType() {
		if (_courseType == null) {
			return "";
		}
		else {
			return _courseType;
		}
	}

	@Override
	public void setCourseType(String courseType) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_courseType = courseType;
	}

	@JSON
	@Override
	public Double getCourseFee() {
		return _courseFee;
	}

	@Override
	public void setCourseFee(Double courseFee) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_courseFee = courseFee;
	}

	@JSON
	@Override
	public boolean getDeleted() {
		return _deleted;
	}

	@JSON
	@Override
	public boolean isDeleted() {
		return _deleted;
	}

	@Override
	public void setDeleted(boolean deleted) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_deleted = deleted;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public boolean getOriginalDeleted() {
		return GetterUtil.getBoolean(
			this.<Boolean>getColumnOriginalValue("deleted"));
	}

	@JSON
	@Override
	public String getStatus() {
		if (_status == null) {
			return "";
		}
		else {
			return _status;
		}
	}

	@Override
	public void setStatus(String status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@JSON
	@Override
	public Date getStartDate() {
		return _startDate;
	}

	@Override
	public void setStartDate(Date startDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_startDate = startDate;
	}

	@JSON
	@Override
	public boolean getUpdated() {
		return _updated;
	}

	@JSON
	@Override
	public boolean isUpdated() {
		return _updated;
	}

	@Override
	public void setUpdated(boolean updated) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_updated = updated;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public boolean getOriginalUpdated() {
		return GetterUtil.getBoolean(
			this.<Boolean>getColumnOriginalValue("updated"));
	}

	@JSON
	@Override
	public boolean getPopular() {
		return _popular;
	}

	@JSON
	@Override
	public boolean isPopular() {
		return _popular;
	}

	@Override
	public void setPopular(boolean popular) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_popular = popular;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public boolean getOriginalPopular() {
		return GetterUtil.getBoolean(
			this.<Boolean>getColumnOriginalValue("popular"));
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Course.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (entry.getValue() != getColumnValue(entry.getKey())) {
				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Course.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Course toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Course>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CourseImpl courseImpl = new CourseImpl();

		courseImpl.setUuid(getUuid());
		courseImpl.setCourseId(getCourseId());
		courseImpl.setGroupId(getGroupId());
		courseImpl.setCompanyId(getCompanyId());
		courseImpl.setUserId(getUserId());
		courseImpl.setUserName(getUserName());
		courseImpl.setCreateDate(getCreateDate());
		courseImpl.setModifiedDate(getModifiedDate());
		courseImpl.setEndDate(getEndDate());
		courseImpl.setVenue(getVenue());
		courseImpl.setAllowOnlinePayment(isAllowOnlinePayment());
		courseImpl.setCourseTitle(getCourseTitle());
		courseImpl.setAllowWebRegistration(isAllowWebRegistration());
		courseImpl.setDescription(getDescription());
		courseImpl.setAvailability(getAvailability());
		courseImpl.setBatchId(getBatchId());
		courseImpl.setWebExpiry(getWebExpiry());
		courseImpl.setFundedCourseFlag(isFundedCourseFlag());
		courseImpl.setCourseCode(getCourseCode());
		courseImpl.setCourseDuration(getCourseDuration());
		courseImpl.setCourseType(getCourseType());
		courseImpl.setCourseFee(getCourseFee());
		courseImpl.setDeleted(isDeleted());
		courseImpl.setStatus(getStatus());
		courseImpl.setStartDate(getStartDate());
		courseImpl.setUpdated(isUpdated());
		courseImpl.setPopular(isPopular());

		courseImpl.resetOriginalValues();

		return courseImpl;
	}

	@Override
	public int compareTo(Course course) {
		int value = 0;

		value = DateUtil.compareTo(getStartDate(), course.getStartDate());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Course)) {
			return false;
		}

		Course course = (Course)object;

		long primaryKey = course.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Course> toCacheModel() {
		CourseCacheModel courseCacheModel = new CourseCacheModel();

		courseCacheModel.uuid = getUuid();

		String uuid = courseCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			courseCacheModel.uuid = null;
		}

		courseCacheModel.courseId = getCourseId();

		courseCacheModel.groupId = getGroupId();

		courseCacheModel.companyId = getCompanyId();

		courseCacheModel.userId = getUserId();

		courseCacheModel.userName = getUserName();

		String userName = courseCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			courseCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			courseCacheModel.createDate = createDate.getTime();
		}
		else {
			courseCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			courseCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			courseCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		Date endDate = getEndDate();

		if (endDate != null) {
			courseCacheModel.endDate = endDate.getTime();
		}
		else {
			courseCacheModel.endDate = Long.MIN_VALUE;
		}

		courseCacheModel.venue = getVenue();

		String venue = courseCacheModel.venue;

		if ((venue != null) && (venue.length() == 0)) {
			courseCacheModel.venue = null;
		}

		courseCacheModel.allowOnlinePayment = isAllowOnlinePayment();

		courseCacheModel.courseTitle = getCourseTitle();

		String courseTitle = courseCacheModel.courseTitle;

		if ((courseTitle != null) && (courseTitle.length() == 0)) {
			courseCacheModel.courseTitle = null;
		}

		courseCacheModel.allowWebRegistration = isAllowWebRegistration();

		courseCacheModel.description = getDescription();

		String description = courseCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			courseCacheModel.description = null;
		}

		courseCacheModel.availability = getAvailability();

		courseCacheModel.batchId = getBatchId();

		String batchId = courseCacheModel.batchId;

		if ((batchId != null) && (batchId.length() == 0)) {
			courseCacheModel.batchId = null;
		}

		Date webExpiry = getWebExpiry();

		if (webExpiry != null) {
			courseCacheModel.webExpiry = webExpiry.getTime();
		}
		else {
			courseCacheModel.webExpiry = Long.MIN_VALUE;
		}

		courseCacheModel.fundedCourseFlag = isFundedCourseFlag();

		courseCacheModel.courseCode = getCourseCode();

		String courseCode = courseCacheModel.courseCode;

		if ((courseCode != null) && (courseCode.length() == 0)) {
			courseCacheModel.courseCode = null;
		}

		Double courseDuration = getCourseDuration();

		if (courseDuration != null) {
			courseCacheModel.courseDuration = courseDuration;
		}

		courseCacheModel.courseType = getCourseType();

		String courseType = courseCacheModel.courseType;

		if ((courseType != null) && (courseType.length() == 0)) {
			courseCacheModel.courseType = null;
		}

		Double courseFee = getCourseFee();

		if (courseFee != null) {
			courseCacheModel.courseFee = courseFee;
		}

		courseCacheModel.deleted = isDeleted();

		courseCacheModel.status = getStatus();

		String status = courseCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			courseCacheModel.status = null;
		}

		Date startDate = getStartDate();

		if (startDate != null) {
			courseCacheModel.startDate = startDate.getTime();
		}
		else {
			courseCacheModel.startDate = Long.MIN_VALUE;
		}

		courseCacheModel.updated = isUpdated();

		courseCacheModel.popular = isPopular();

		return courseCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Course, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Course, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Course, Object> attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Course)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Course, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Course, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Course, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Course)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Course>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private long _courseId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private Date _endDate;
	private String _venue;
	private boolean _allowOnlinePayment;
	private String _courseTitle;
	private boolean _allowWebRegistration;
	private String _description;
	private int _availability;
	private String _batchId;
	private Date _webExpiry;
	private boolean _fundedCourseFlag;
	private String _courseCode;
	private Double _courseDuration;
	private String _courseType;
	private Double _courseFee;
	private boolean _deleted;
	private String _status;
	private Date _startDate;
	private boolean _updated;
	private boolean _popular;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Course, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Course)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("courseId", _courseId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("endDate", _endDate);
		_columnOriginalValues.put("venue", _venue);
		_columnOriginalValues.put("allowOnlinePayment", _allowOnlinePayment);
		_columnOriginalValues.put("courseTitle", _courseTitle);
		_columnOriginalValues.put(
			"allowWebRegistration", _allowWebRegistration);
		_columnOriginalValues.put("description", _description);
		_columnOriginalValues.put("availability", _availability);
		_columnOriginalValues.put("batchId", _batchId);
		_columnOriginalValues.put("webExpiry", _webExpiry);
		_columnOriginalValues.put("fundedCourseFlag", _fundedCourseFlag);
		_columnOriginalValues.put("courseCode", _courseCode);
		_columnOriginalValues.put("courseDuration", _courseDuration);
		_columnOriginalValues.put("courseType", _courseType);
		_columnOriginalValues.put("courseFee", _courseFee);
		_columnOriginalValues.put("deleted", _deleted);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("startDate", _startDate);
		_columnOriginalValues.put("updated", _updated);
		_columnOriginalValues.put("popular", _popular);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("courseId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("endDate", 256L);

		columnBitmasks.put("venue", 512L);

		columnBitmasks.put("allowOnlinePayment", 1024L);

		columnBitmasks.put("courseTitle", 2048L);

		columnBitmasks.put("allowWebRegistration", 4096L);

		columnBitmasks.put("description", 8192L);

		columnBitmasks.put("availability", 16384L);

		columnBitmasks.put("batchId", 32768L);

		columnBitmasks.put("webExpiry", 65536L);

		columnBitmasks.put("fundedCourseFlag", 131072L);

		columnBitmasks.put("courseCode", 262144L);

		columnBitmasks.put("courseDuration", 524288L);

		columnBitmasks.put("courseType", 1048576L);

		columnBitmasks.put("courseFee", 2097152L);

		columnBitmasks.put("deleted", 4194304L);

		columnBitmasks.put("status", 8388608L);

		columnBitmasks.put("startDate", 16777216L);

		columnBitmasks.put("updated", 33554432L);

		columnBitmasks.put("popular", 67108864L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Course _escapedModel;

}